#!/usr/bin/env bash
# landresolve_ac_intent_card_refresh_path.sh —
# LIVE DEFECT 2026-09-18 (mcphost-test-suite-consolidation dispatch
# 20260918T193320Z-3339733): land-resolve.sh's generated-file regen
# step evaluates a policy's `regen` command with cwd=$repo, which is
# correct for a repo-owned generator (mcphost's own
# scripts/gen-test-suites.sh) but silently mis-resolved a build-skill-
# owned generator like scripts/intent-card-refresh.sh — that script
# lives under $SKILL_DIR, not under $repo, so `eval`ing the raw
# "scripts/intent-card-refresh.sh" string with cwd=$repo failed with
# "No such file or directory" (land-resolve.sh:421) and left
# agent/intent-card.json's rebase conflict unresolved twice in a row.
#
# Given a fixture repo whose cwd is NOT the build-skill dir, with a
# land-policy regen command naming a script that exists only under
# $SKILL_DIR/scripts (never copied into the repo) — the same shape as
# the real "scripts/intent-card-refresh.sh" entry — When land-resolve.sh
# resolve runs a rebase-conflict auto-regen, Then it finds and invokes
# that SKILL_DIR-owned script (exit 0, no "No such file"), not just a
# repo-owned one, and the regen output lands.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
RESOLVE="$HERE/../scripts/land-resolve.sh"
[ -x "$RESOLVE" ] || { echo "FAIL: $RESOLVE not executable" >&2; exit 2; }
command -v jq >/dev/null 2>&1 || { echo "FAIL: jq required" >&2; exit 2; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
REPO="$WORK/repo"
git init -q -b main "$REPO"
git -C "$REPO" config user.email a@b.c
git -C "$REPO" config user.name test

# The generated file's real regen tool lives ONLY under a fake
# $SKILL_DIR/scripts — never copied into the target repo — mirroring
# the real scripts/intent-card-refresh.sh, which lives in build-skill's
# own scripts/, not in the repo it regenerates.
SKILL="$WORK/skill"
mkdir -p "$SKILL/scripts"
cat >"$SKILL/scripts/intent-card-refresh.sh" <<'EOF'
#!/usr/bin/env bash
# Stand-in for the real scripts/intent-card-refresh.sh: its presence at
# $SKILL_DIR/scripts (not $repo/scripts) is the whole point of this
# fixture — if land-resolve.sh only ever looked under $repo, this file
# would never run.
echo "generated-canonical-v1" > agent-card.txt
EOF
chmod +x "$SKILL/scripts/intent-card-refresh.sh"

( cd "$REPO" && "$SKILL/scripts/intent-card-refresh.sh" )
git -C "$REPO" add -A
git -C "$REPO" commit -q -m base

git -C "$REPO" checkout -q -b autobuilder/fix1
echo "src-change" > "$REPO/src.txt"
git -C "$REPO" add -A
git -C "$REPO" commit -q -m "branch source change"
echo "generated-canonical-v1-branch-variant" > "$REPO/agent-card.txt"
git -C "$REPO" commit -q -am "branch variant of agent-card.txt"

git -C "$REPO" checkout -q main
echo "generated-canonical-v1-main-variant" > "$REPO/agent-card.txt"
git -C "$REPO" commit -q -am "main variant of agent-card.txt"

git -C "$REPO" checkout -q autobuilder/fix1

# Policy: agent-card.txt is generated by a script named the exact
# repo-relative-looking shape the real broken policy used
# (`scripts/<name>.sh`) for a build-skill-owned generator.
export BUILD_STATE_DIR="$WORK/state"
export BUILD_SKILL_DIR="$SKILL"
mkdir -p "$BUILD_STATE_DIR/land-policy"
cat >"$BUILD_STATE_DIR/land-policy/repo.json" <<'EOF'
{"generated": [{"path": "agent-card.txt", "regen": "scripts/intent-card-refresh.sh"}], "append_only": []}
EOF

git -C "$REPO" rebase main >/dev/null 2>&1 || true
conflicted_before="$(git -C "$REPO" diff --name-only --diff-filter=U)"

fail=0
if [ "$conflicted_before" = "agent-card.txt" ]; then
  echo "ok  AC: fixture produced a real rebase conflict in agent-card.txt"
else
  echo "FAIL: expected a conflict in agent-card.txt, got '$conflicted_before'" >&2
  fail=1
fi

out="$("$RESOLVE" resolve "$REPO" fix1 2>"$WORK/stderr.log")"; rc=$?
stderr="$(cat "$WORK/stderr.log")"

if [ "$rc" -eq 0 ] && [ "$out" = "resolved=all" ]; then
  echo "ok  AC: land-resolve resolve reports resolved=all (rc=0)"
else
  echo "FAIL: expected rc=0/resolved=all, got rc=$rc out='$out' stderr='$stderr'" >&2
  fail=1
fi

if ! printf '%s' "$stderr" | grep -q "No such file"; then
  echo "ok  AC: no 'No such file' error resolving the SKILL_DIR-owned regen script"
else
  echo "FAIL: stderr still contains 'No such file': $stderr" >&2
  fail=1
fi

if [ -z "$(git -C "$REPO" status --porcelain)" ]; then
  echo "ok  AC: rebase completed, working tree clean"
else
  echo "FAIL: working tree not clean after resolve: $(git -C "$REPO" status --porcelain)" >&2
  fail=1
fi

content="$(cat "$REPO/agent-card.txt" 2>/dev/null)"
if [ "$content" = "generated-canonical-v1" ]; then
  echo "ok  AC: landed agent-card.txt equals the SKILL_DIR script's regen output"
else
  echo "FAIL: expected regen output, got '$content'" >&2
  fail=1
fi

exit $fail
