#!/usr/bin/env bash
# cli-register.sh — merge-safe CLI subcommand registration
#
# Usage:
#   cli-register.sh <repo_path> <subcmd_name> <module_path>
#
# Creates a NEW per-subcommand sidecar file:
#   src/register/<subcmd_name>.register
#
# Each sidecar contains the subcommand's registration metadata.
# The actual dispatcher wiring is generated by `cli-assemble.sh`.
# Because every branch creates a DIFFERENT new file, parallel branches that
# each register a distinct subcommand produce non-overlapping diffs that
# `git merge` auto-resolves with zero conflicts.
#
# Exit codes:
#   0  — success (created or already exists — no-op)
#   1  — usage / argument error
#   2  — repo path invalid
#
# Back-compat: repos that do NOT call cli-register.sh are entirely unaffected.
# The sidecar files and assembled dispatcher are purely additive and opt-in.
#
# Two-step workflow:
#   1. cli-register.sh <repo> <SubcmdName> <module_path>
#      → creates src/register/<SubcmdName>.register  (committed on each branch)
#   2. cli-assemble.sh <repo>
#      → reads all src/register/*.register files
#      → writes the generated enum + match arms between anchor comments
#        in src/main.rs
#      (called once after all branches are integrated, before the version bump)
#
# See SKILL.md "Worktree isolation / Merge-safe CLI dispatch" for context.

set -euo pipefail

die() { local code="$1"; shift; echo "cli-register: $*" >&2; exit "$code"; }

usage() {
    cat >&2 <<'EOF'
usage: cli-register.sh <repo_path> <subcmd_name> <module_path>

Arguments:
  repo_path    Absolute path to the git repo root
  subcmd_name  PascalCase subcommand name (e.g. "Bridge", "Remedy")
  module_path  Rust module path prefix for the run() fn (e.g. "bridge", "remedy::cmd")

Examples:
  cli-register.sh /home/jsy/wintermute/concord Bridge bridge
  cli-register.sh /home/jsy/wintermute/quicken Remedy remedy::cmd

Exit codes: 0=ok/noop  1=usage  2=invalid repo
EOF
    exit 1
}

# ── arg check ────────────────────────────────────────────────────────────────
[ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ] && usage
[ $# -lt 3 ] && usage

REPO="$1"
SUBCMD="$2"    # PascalCase: e.g. "Bridge"
MODULE="$3"    # module path: e.g. "bridge" or "bridge::cmd"

# ── validate repo ────────────────────────────────────────────────────────────
[ -d "$REPO" ] || die 2 "repo path not found: $REPO"

# ── create sidecar registration file (idempotent) ────────────────────────────
REGISTER_DIR="$REPO/src/register"
mkdir -p "$REGISTER_DIR"

SIDECAR="$REGISTER_DIR/${SUBCMD}.register"
if [ -f "$SIDECAR" ]; then
    echo "cli-register: $SUBCMD already registered at $SIDECAR — no-op" >&2
    exit 0
fi

cat > "$SIDECAR" <<EOF
# cli-register sidecar — do not edit manually; managed by scripts/cli-register.sh
subcmd=${SUBCMD}
module=${MODULE}
EOF

echo "cli-register: registered $SUBCMD -> $MODULE (sidecar: $SIDECAR)" >&2
exit 0
