#!/usr/bin/env bash
# extend-gate.sh — regenerate autobuilder's 25 receipts at HEAD on a
# rust-extend crate's main checkout, so the deploy gate a rust-extend ship
# reads is never bound to a stale commit. PRD-build-extend-gate-receipts.
#
# usage: extend-gate.sh <build_into> [--base <tag>] [--head <sha>] [--dry-run]
#                        [--project-root <rel>]
#                        [--parallelism N] [--record-baseline] [--force]
#
# On a clean main checkout, at HEAD, in this order:
#   scripts/audit.sh                         (if the crate has one)
#   autobuilder intake --validate agent/intent-card.json --project <root>
#     (writes receipts/intake.json fresh at HEAD — PRD-build-gate-producers;
#     before that PRD, nothing in this sequence ever passed --project, so
#     intake.json was never regenerated by a live gate run)
#   autobuilder loop --project <root> --iteration 0 --head-sha <HEAD> --trace
#   autobuilder vti-plan
#   autobuilder rollback-plan --base <base>
#   autobuilder reviewer-agent prepare --base <base>, then finalize
#     (the binary cannot spawn its own subagent — see
#     autobuilder/src/reviewer.rs — so this script spawns a headless
#     sonnet review via `claude -p` and feeds its JSON to finalize)
#   autobuilder ci-checks
#   ~/.claude/skills/rustbuild/scripts/extended-receipts.sh <root> [parallelism]
#   autobuilder gate --project <root>
# <root> is normally <build_into> itself, but is resolved to the nearest
# subdirectory containing Cargo.toml when <build_into> has none at its own
# root (see "cargo project root resolution" below).
# <base> defaults to the newest `v<major>.<minor>.<patch>` tag reachable
# from HEAD by first-parent (autobuilder's own rollback-plan convention),
# falling back to the crate's initial commit when no such tag exists.
#
# Prints the gate's own summary line (`gate: head=... pass=N block=M
# verdict=...`) and exits with the gate's verdict.
#
# Delta verdict against a committed baseline (PRD-build-gate-delta-baseline).
# `autobuilder gate`'s own pass/block is not the final word: this script
# additionally diffs the blocking receipt set against
# `<build_into>/agent/gate-baseline.json` AT HEAD (a working-tree-only copy
# never counts — fail closed) via `scripts/gate-delta.sh verdict`, and
# prints its own summary line:
#   extend-gate: delta verdict=pass|delta-pass|block baseline=present|absent new_blocks=<...> inherited_blocks=<...>
# `delta-pass` means block>0 but every blocking receipt name is already in
# the baseline — this script then exits 0 (shippable), same as a plain
# `pass`. `block` means at least one blocking receipt is NOT in the
# baseline (or there is no committed baseline at all — today's behavior,
# preserved byte-for-byte: no baseline means this new summary line and the
# exit code are unaffected by anything above). `--record-baseline` writes
# the baseline from the CURRENT run's blocking set instead of computing a
# verdict against one — see that flag's own note below. A verdict run
# never writes or widens the baseline itself.
#
# <build_into> is normally both the git repo root and the Cargo project
# root (mcphost, wm-node, adopt) — but that's not universal. When the repo
# root has no Cargo.toml (rustbuild's has always lived one level down, at
# autobuilder/Cargo.toml), immediate subdirectories are searched (depth 1,
# then depth 2 if depth 1 finds nothing — never descending into target/ or
# .git/) for exactly one Cargo.toml, and THAT resolved path is passed to
# every producer below (including extended-receipts.sh's 17) instead of
# the repo root, so cargo-invoking producers stop exiting 101 for "could
# not find Cargo.toml" against a directory that was never the actual
# crate. A repo with a root Cargo.toml AND a nested one keeps the root,
# unchanged (no search triggered). Ambiguous (>1 candidate) or absent (0
# candidates) fails loudly (exit 6) naming what was searched, before any
# producer runs — never a silent 101. PRD-build-extend-gate-nested-crate-project.
#
# Exit codes:
#   0  gate verdict pass (pass=25 block=0) OR delta-pass (block>0 but every
#      blocking receipt is in the committed baseline) OR a successful
#      `--record-baseline` write (that mode's exit code reports the write,
#      not the underlying pass/block)
#   1  gate verdict block (one or more receipts failed, and at least one
#      of them is not in the committed baseline — or there is no committed
#      baseline at all)
#   1  usage error (bad/missing arguments)
#   2  a required binary is missing from $PATH (autobuilder, extended-receipts.sh,
#      ship-tag.sh, gate-delta.sh, jq) — cannot even attempt a run
#   3  dirty tree — refused before any producer ran, nothing under
#      target/autobuilder/ changed
#   4  could not acquire the per-repo integration lock within
#      $EXTEND_GATE_PRODUCER_LOCK_WAIT seconds (default 90 — PRD-build-
#      extend-gate-concurrent-isolation requirement 2). The message names
#      the contending pid(s) ("producer-lock-contended, pid=<n>[,<n>...]"),
#      is refused before any producer ran, and never emits a `gate: ...
#      pass=.../block=...` verdict line — fail-closed, not fail-wrong.
#   5  --head <sha> does not match actual HEAD — refused before any
#      producer ran
#   6  could not resolve a unique Cargo project root under <build_into>
#      (none found, or more than one candidate) — refused before any
#      producer ran
#   7  installed `autobuilder` binary is STALE — its `--version` is older
#      than the canonical crate's `[package] version` in
#      $AUTOBUILDER_CANONICAL_CARGO_TOML — refused before any producer ran
#      (AC4, PRD-autobuilder-source-unify). The message names the
#      installed version, the expected (canonical) version, and the exact
#      `cargo install --path <canonical-crate-dir> --locked` fix. Skipped
#      (not an error) when the canonical Cargo.toml itself is absent —
#      e.g. a test HOME with no checked-out canonical crate — since this
#      guard is about staleness, not about requiring the canonical source
#      to exist on every box that runs a gate.
#
# --record-baseline: runs the full producer sequence exactly as a normal
# invocation, then instead of computing a delta verdict, writes
# `<build_into>/agent/gate-baseline.json` from THIS run's blocking receipt
# set (`scripts/gate-delta.sh record`) and prints the recorded document.
# Meant to be committed by the caller (a human, or an explicit gate-debt
# PRD) — this script never commits, and a plain verdict run never widens
# or auto-records a baseline on its own. Bypasses the verdict cache below
# (a recording always reflects a fresh run). Exits 0 on a successful
# write regardless of the underlying pass/block count.
#
# Verdict cache: on a successful (non-dry-run, non-record-baseline) run,
# the computed verdict is cached at
# `<project>/target/autobuilder/last-verdict.json` keyed on (HEAD sha,
# this script's own sha256). A later invocation at the SAME head with an
# UNCHANGED script replays the cached verdict (`extend-gate: verdict=...
# (cached)`, same exit code) instead of regenerating all 25 receipts.
# `--force` bypasses the cache and always runs the full sequence.
#
# Never runs `cargo clean` in the crate's own target/ (determinism and
# cold-build-time already build in their own temp target dirs — memory
# rule: never `cargo clean` a crate with receipts).
#
# Takes the SAME per-repo integration lock `worktree-extend.sh integrate`
# takes (`<repo>/.git/autobuilder-integrate.lock`, `flock`), held from
# BEFORE the first producer runs (scripts/audit.sh) through the final
# `autobuilder gate` accounting step, so two PRDs landing on one crate in
# one tick — or N concurrent gate invocations dispatched against one
# shared build_into in the same tick, PRD-build-extend-gate-concurrent-
# isolation — never run producers concurrently: the second (and every
# subsequent) run waits for the lock, then regenerates receipts at the
# HEAD it sees once it acquires it (the later HEAD, if one landed in the
# meantime). A run that cannot acquire the lock within
# $EXTEND_GATE_PRODUCER_LOCK_WAIT seconds (default 90) fails closed — see
# exit code 4 below — rather than ever reading a receipt set another
# invocation may still be mid-write on.
#
# --dry-run prints the producer sequence, the resolved base tag, and HEAD;
# writes nothing under target/autobuilder/; never takes the lock; exits 0.
#
# Individual producer steps are run best-effort: a non-zero exit from any
# one of them (rollback-plan finding a non-revert-clean merge, ci-checks
# finding a red workflow, ...) is logged and the run CONTINUES through the
# rest of the sequence, so every receipt gets regenerated at HEAD and the
# final `autobuilder gate` is the single source of truth for pass/block —
# an early abort would leave the receipt set partial and mislead the next
# tick about which check actually failed. Per requirement 7 (resumable): a
# tick that ends mid-gate leaves a partial receipt set, which is never
# read as green; the next tick reruns this script from the start.
set -uo pipefail
export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"

# Overridable so tests/ can point at a fixture dir of fake binaries
# without touching production behavior (default unchanged).
RUSTBUILD_SCRIPTS="${RUSTBUILD_SCRIPTS:-$HOME/.claude/skills/rustbuild/scripts}"
REVIEWER_PROMPT="${REVIEWER_PROMPT:-$HOME/.claude/skills/rustbuild/prompts/reviewer-agent.md}"
# Canonical autobuilder crate Cargo.toml — the install-freshness guard
# (AC4, PRD-autobuilder-source-unify, exit 7 below) reads its
# `[package] version` and compares it to the installed `autobuilder
# --version`. Overridable so tests/ can point at a fixture Cargo.toml
# without touching production behavior (default unchanged: the split
# repo's nested crate root, matching this fleet's `--project-root
# autobuilder` convention).
AUTOBUILDER_CANONICAL_CARGO_TOML="${AUTOBUILDER_CANONICAL_CARGO_TOML:-$HOME/wintermute/autobuilder/autobuilder/Cargo.toml}"
BUILD_SCRIPTS="$(cd "$(dirname "$0")" && pwd)"
GATE_DELTA="$BUILD_SCRIPTS/gate-delta.sh"
# Three-state retrofit (PRD-build-three-state-probes): fail-open sourcing so
# an unshipped/missing library never breaks a gate run.
if [ -r "$BUILD_SCRIPTS/probe-result.sh" ]; then
  # shellcheck source=probe-result.sh
  source "$BUILD_SCRIPTS/probe-result.sh"
else
  probe_emit() { :; }
fi
# PRD-build-cargo-concurrency-budget: every producer step below that shells
# to cargo (the proof-receipt loop and the 17 extended producers) takes a
# budget slot for its whole phase instead of assuming it owns the host —
# see cargo-budget.sh's header for why (RedBaron OOMed for ~6min at
# load 21,466 on 2026-09-09 with the sub-cap at 3). Overridable so tests/
# can point at a fixture wrapper without touching production behavior.
CARGO_BUDGET="${CARGO_BUDGET:-$BUILD_SCRIPTS/cargo-budget.sh}"
# PRD-build-extend-gate-concurrent-isolation: the producer-lock wait below
# (requirement 2 — bounded wait, explicit fail-closed) is its own ceiling,
# distinct from worktree-extend.sh integrate's own ~120s wait on the SAME
# lock file and from manifest-set.sh's unrelated 60s manifest-write
# ceiling — overridable so a selftest can force contention/timeout in
# seconds instead of minutes without touching production behavior
# (default unchanged in spirit, just named and shortened from the prior
# unconditional 120 to the PRD's specified 90).
EXTEND_GATE_PRODUCER_LOCK_WAIT="${EXTEND_GATE_PRODUCER_LOCK_WAIT:-90}"
# PRD-build-burst-pull-on-demand requirement 2: this IS the gate harness's
# own local-cargo choke point — every producer below (the proof-receipt
# loop's `autobuilder loop` AND extended-receipts.sh's 17 producers) funnels
# through cargo_budgeted, always running LOCALLY (cargo-budget.sh is a local
# concurrency cap, never a remote route). A burst-lane `run` elsewhere may
# have left $repo's target/ remote-dirty in the meantime; overridable so
# tests/ can point at a fixture without touching production behavior.
BURST_LANE_SH="${BURST_LANE_SH:-$BUILD_SCRIPTS/burst-lane.sh}"
cargo_budgeted() {
  # Fails open (never blocks the gate) if burst-lane.sh is missing or the
  # pull itself fails — this gate must still run against whatever is on
  # disk rather than turn a lazy-pull hiccup into a gate outage.
  if [ -x "$BURST_LANE_SH" ]; then
    "$BURST_LANE_SH" ensure-fresh "$repo" >/dev/null 2>&1 || true
  fi
  # Runs "$@" through the budget wrapper when it's present+executable;
  # fails open (runs "$@" directly) if cargo-budget.sh is missing so a
  # partial checkout never turns a missing helper into a gate outage.
  if [ -x "$CARGO_BUDGET" ]; then
    "$CARGO_BUDGET" run -- "$@"
  else
    "$@"
  fi
}

die() { echo "extend-gate: $2" >&2; exit "$1"; }

usage() {
  cat <<'EOF'
usage: extend-gate.sh <build_into> [--base <tag>] [--head <sha>] [--dry-run]
                       [--parallelism N] [--record-baseline] [--force]
EOF
}

producers_desc() {
  cat <<'EOF'
scripts/audit.sh (if present)
autobuilder intake --validate agent/intent-card.json --project <root>
autobuilder loop --project <root> --iteration 0 --head-sha <HEAD> --trace
autobuilder vti-plan
autobuilder rollback-plan --base <base>
autobuilder reviewer-agent prepare --base <base> ; claude -p (headless sonnet review) ; autobuilder reviewer-agent finalize
autobuilder ci-checks
extended-receipts.sh <root> [parallelism]  (17 extended producers)
autobuilder gate --project <root>
EOF
}

[ $# -ge 1 ] || { usage >&2; exit 1; }
case "$1" in -h|--help) usage; exit 0 ;; esac
repo_arg="$1"; shift

base_override=""
head_want=""
dry_run=false
parallelism=6
record_baseline=false
force=false
project_root_override=""

while [ $# -gt 0 ]; do
  case "$1" in
    --base)             base_override="${2:?extend-gate: --base needs a value}"; shift 2 ;;
    --head)             head_want="${2:?extend-gate: --head needs a value}"; shift 2 ;;
    --dry-run)          dry_run=true; shift ;;
    --parallelism)      parallelism="${2:?extend-gate: --parallelism needs a value}"; shift 2 ;;
    --record-baseline)  record_baseline=true; shift ;;
    --force)            force=true; shift ;;
    --project-root)     project_root_override="${2:?extend-gate: --project-root needs a value}"; shift 2 ;;
    *) die 1 "unknown argument: $1 (see --help)" ;;
  esac
done

repo="$(cd "$repo_arg" 2>/dev/null && pwd)" || die 1 "no such directory: $repo_arg"
git -C "$repo" rev-parse --git-dir >/dev/null 2>&1 || die 1 "not a git repo: $repo"
command -v autobuilder >/dev/null 2>&1 || die 2 "autobuilder not on \$PATH (cargo install --path ~/wintermute/rustbuild/autobuilder --locked)"
[ -x "$RUSTBUILD_SCRIPTS/extended-receipts.sh" ] || die 2 "missing $RUSTBUILD_SCRIPTS/extended-receipts.sh"
[ -x "$RUSTBUILD_SCRIPTS/ship-tag.sh" ] || die 2 "missing $RUSTBUILD_SCRIPTS/ship-tag.sh"
[ -x "$GATE_DELTA" ] || die 2 "missing $GATE_DELTA"
command -v jq >/dev/null 2>&1 || die 2 "jq not on \$PATH (needed by gate-delta.sh)"

# --- install-freshness guard (AC4, PRD-autobuilder-source-unify) --------
# The installed `autobuilder` binary is the tool every producer below
# shells out to (intake, loop, vti-plan, rollback-plan, reviewer-agent,
# ci-checks, gate) — ITS OWN crate version, not $repo's, is what matters
# here: a binary older than the canonical crate silently runs
# feature-incomplete checks (e.g. an old rollback model) and produces
# receipts that look green but aren't. Refused before any producer runs,
# and before the project-root search / integration lock below, since
# neither needs to happen for a run this guard is about to block anyway.
# See exit code 7 above for the absent-canonical-Cargo.toml skip case.
canonical_crate_version() {
  local toml="$1" in_pkg=0 line
  [ -f "$toml" ] || return 1
  while IFS= read -r line; do
    case "$line" in
      '[package]') in_pkg=1; continue ;;
      '['*)        in_pkg=0; continue ;;
    esac
    if [ "$in_pkg" -eq 1 ]; then
      case "$line" in
        version\ =\ \"*\"|version=\"*\")
          line="${line#*\"}"
          printf '%s\n' "${line%%\"*}"
          return 0
          ;;
      esac
    fi
  done < "$toml"
  return 1
}

version_lt() {
  [ "$1" = "$2" ] && return 1
  local lowest
  lowest="$(printf '%s\n%s\n' "$1" "$2" | sort -t. -k1,1n -k2,2n -k3,3n | head -1)"
  [ "$lowest" = "$1" ]
}

if canonical_version="$(canonical_crate_version "$AUTOBUILDER_CANONICAL_CARGO_TOML")" && [ -n "$canonical_version" ]; then
  installed_version="$(autobuilder --version 2>/dev/null | awk '{print $NF}')"
  if [ -z "$installed_version" ]; then
    probe_emit gate-receipt-freshness could-not-check "could not parse 'autobuilder --version' output (canonical expects $canonical_version)" >/dev/null
    die 2 "could not parse 'autobuilder --version' output to determine the installed version (canonical crate expects $canonical_version at $AUTOBUILDER_CANONICAL_CARGO_TOML)"
  fi
  if version_lt "$installed_version" "$canonical_version"; then
    probe_emit gate-receipt-freshness dirty "installed=$installed_version expected=$canonical_version — receipts about to be regenerated by a stale binary" >/dev/null
    canonical_dir="$(dirname "$AUTOBUILDER_CANONICAL_CARGO_TOML")"
    die 7 "installed autobuilder binary is STALE — installed=$installed_version expected=$canonical_version (canonical crate: $AUTOBUILDER_CANONICAL_CARGO_TOML) — fix: cargo install --path $canonical_dir --locked"
  fi
  probe_emit gate-receipt-freshness clean "installed=$installed_version expected=$canonical_version (fresh)" >/dev/null
else
  # Previously a bare informational echo — which reads exactly like the
  # PRD's silent-failure class: "the guard found nothing to block on" and
  # "the guard could not even determine whether to block" printed the same
  # shape (a skip line) and were indistinguishable downstream. Now recorded
  # explicitly as could-not-check rather than folded into an implicit clean.
  probe_emit gate-receipt-freshness could-not-check "no canonical crate Cargo.toml at $AUTOBUILDER_CANONICAL_CARGO_TOML" >/dev/null
  echo "extend-gate: no canonical crate Cargo.toml at $AUTOBUILDER_CANONICAL_CARGO_TOML — skipping install-freshness guard" >&2
fi

# --- cargo project root resolution (PRD-build-extend-gate-nested-crate-project) ---
# $repo itself wins immediately if it has a Cargo.toml (the common case,
# and the edge case of a repo with both a root AND a nested Cargo.toml —
# root wins, no search performed at all, so byte-identical behavior for
# every already-onboarded crate). Otherwise search one level down, then
# two, for exactly one Cargo.toml, skipping target/ and .git/ at every
# level. Prints the resolved path on success; prints a human-readable
# reason (ambiguous / absent, naming what was searched) on failure.
find_cargo_root() {
  local base="$1"
  if [ -f "$base/Cargo.toml" ]; then
    printf '%s\n' "$base"
    return 0
  fi
  local d b
  local -a d1=()
  for d in "$base"/*/; do
    [ -d "$d" ] || continue
    b="$(basename "$d")"
    case "$b" in target|.git) continue ;; esac
    [ -f "$d/Cargo.toml" ] && d1+=("${d%/}")
  done
  if [ "${#d1[@]}" -eq 1 ]; then
    printf '%s\n' "${d1[0]}"
    return 0
  elif [ "${#d1[@]}" -gt 1 ]; then
    # Disambiguate the common <repo>/<repo>/Cargo.toml nesting pattern: if
    # exactly one candidate's basename matches the repo's own basename,
    # prefer it over unrelated sibling dirs (e.g. a "tools/" cargo
    # workspace). Only fires inside this already-ambiguous branch, so
    # repos without this exact collision are unaffected.
    local base_name="$(basename "$base")" self_match="" self_count=0 cand
    for cand in "${d1[@]}"; do
      if [ "$(basename "$cand")" = "$base_name" ]; then
        self_match="$cand"
        self_count=$((self_count + 1))
      fi
    done
    if [ "$self_count" -eq 1 ]; then
      printf '%s\n' "$self_match"
      return 0
    fi
    printf 'ambiguous — multiple Cargo.toml found one level under %s: %s' "$base" "${d1[*]}"
    return 1
  fi
  local d1dir b1 d2dir b2
  local -a d2=()
  for d1dir in "$base"/*/; do
    [ -d "$d1dir" ] || continue
    b1="$(basename "$d1dir")"
    case "$b1" in target|.git) continue ;; esac
    for d2dir in "$d1dir"*/; do
      [ -d "$d2dir" ] || continue
      b2="$(basename "$d2dir")"
      case "$b2" in target|.git) continue ;; esac
      [ -f "$d2dir/Cargo.toml" ] && d2+=("${d2dir%/}")
    done
  done
  if [ "${#d2[@]}" -eq 1 ]; then
    printf '%s\n' "${d2[0]}"
    return 0
  elif [ "${#d2[@]}" -gt 1 ]; then
    # Same repo-basename tie-break as the one-level-down case, mirrored
    # for consistency (untested pattern — the one-level case above is the
    # one actually observed).
    local base_name2="$(basename "$base")" self_match2="" self_count2=0 cand2
    for cand2 in "${d2[@]}"; do
      if [ "$(basename "$cand2")" = "$base_name2" ]; then
        self_match2="$cand2"
        self_count2=$((self_count2 + 1))
      fi
    done
    if [ "$self_count2" -eq 1 ]; then
      printf '%s\n' "$self_match2"
      return 0
    fi
    printf 'ambiguous — multiple Cargo.toml found two levels under %s: %s' "$base" "${d2[*]}"
    return 1
  fi
  printf 'no Cargo.toml found at %s, in its immediate subdirectories, or two levels down (searched depth-1 and depth-2, excluding target/ and .git/)' "$base"
  return 1
}

# --project-root <rel>: explicit disambiguation when find_cargo_root's
# one-crate rule can't decide (e.g. sibling crates one level down, like
# autobuilder/ + tools/). Relative to the repo; must contain a Cargo.toml.
if [ -n "$project_root_override" ]; then
  project_abs="$repo/$project_root_override"
  [ -f "$project_abs/Cargo.toml" ] || die 6 "no Cargo.toml at --project-root $project_root_override (looked in $project_abs)"
else
  project_abs="$(find_cargo_root "$repo")" || die 6 "$project_abs"
fi
project_rel="$(realpath --relative-to="$repo" "$project_abs")"

# --- base resolution ---------------------------------------------------
# Mirrors autobuilder rollback-plan's own default exactly (see
# autobuilder/src/rollback.rs newest_reachable_tag/resolve_default_base):
# walk first-parent history from HEAD backward, take the newest
# v<major>.<minor>.<patch> tag found; else the crate's initial commit.
# Computed here (not just left to rollback-plan's own default) so
# --dry-run can report it without running any producer, and so
# reviewer-agent prepare reviews the SAME range rollback-plan checks
# (user story 5: <last-tag>..HEAD, not a branch that no longer exists).
newest_reachable_tag() {
  local sha tags best
  while read -r sha; do
    [ -n "$sha" ] || continue
    tags="$(git -C "$repo" tag --points-at "$sha" 2>/dev/null | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || true)"
    [ -n "$tags" ] || continue
    best="$(printf '%s\n' $tags | sed 's/^v//' | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)"
    printf 'v%s\n' "$best"
    return 0
  done < <(git -C "$repo" rev-list --first-parent HEAD 2>/dev/null)
  return 1
}

resolve_base() {
  if [ -n "$base_override" ]; then
    printf '%s\n' "$base_override"
    return 0
  fi
  local t
  if t="$(newest_reachable_tag)"; then
    printf '%s\n' "$t"
    return 0
  fi
  git -C "$repo" rev-list --max-parents=0 HEAD 2>/dev/null | tail -1
}

# --- tag-lineage self-heal ----------------------------------------------
# 2026-09-09: parallel-integrate branch agents bumped 0.32.0-0.34.0 without
# tagging; one missing tag turned rollback-plan red for every sibling PRD
# sharing the repo. Tagging is bookkeeping on commits that already exist, so
# the gate repairs it deterministically instead of trusting agent prompts:
# walk first-parent from HEAD to the newest existing v-tag (bounded), and for
# every commit whose crate version changed, create + push the missing tag.
backfill_version_tags() {
  local manifest="$project_rel/Cargo.toml"
  [ "$project_rel" = "." ] && manifest="Cargo.toml"
  # The CURRENT version (what HEAD's Cargo.toml declares) is never backfilled:
  # the redeploy-tag producer owns placing it on the green HEAD. Backfill only
  # heals HISTORICAL lineage (versions already superseded by a later bump).
  local current_ver
  current_ver="$(git -C "$repo" show "HEAD:$manifest" 2>/dev/null | sed -n 's/^version *= *"\([0-9.]*\)".*/\1/p' | head -1)"
  local sha ver parent pver n=0
  while read -r sha; do
    n=$((n + 1)); [ "$n" -gt 100 ] && break
    # stop at the newest already-tagged commit — lineage below it is history
    if git -C "$repo" tag --points-at "$sha" 2>/dev/null | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
      [ "$n" -gt 1 ] && break
      continue
    fi
    ver="$(git -C "$repo" show "$sha:$manifest" 2>/dev/null | sed -n 's/^version *= *"\([0-9.]*\)".*/\1/p' | head -1)"
    [ -n "$ver" ] || continue
    parent="$(git -C "$repo" rev-parse "$sha^" 2>/dev/null)" || continue
    pver="$(git -C "$repo" show "$parent:$manifest" 2>/dev/null | sed -n 's/^version *= *"\([0-9.]*\)".*/\1/p' | head -1)"
    [ "$ver" = "$current_ver" ] && continue
    if [ "$ver" != "$pver" ] && ! git -C "$repo" rev-parse "v$ver" >/dev/null 2>&1; then
      git -C "$repo" tag "v$ver" "$sha" 2>/dev/null \
        && echo "extend-gate: tag-lineage self-heal — created v$ver at ${sha:0:9}" >&2 \
        && git -C "$repo" push origin "refs/tags/v$ver" >/dev/null 2>&1 || true
    fi
  done < <(git -C "$repo" rev-list --first-parent HEAD 2>/dev/null)
}
backfill_version_tags

# Executable "shipped" contract — hard enforcement point. backfill above heals
# the mechanical (tag) case; anything still failing is a real shipping defect.
if ! "$BUILD_SCRIPTS/ship-postconditions.sh" "$repo" --project-root "$project_rel"; then
  die 1 "ship-postconditions failed for $repo (project-root $project_rel) — see FAIL lines above"
fi

head_now="$(git -C "$repo" rev-parse HEAD 2>/dev/null)"
base_ref="$(resolve_base)"

if $dry_run; then
  echo "extend-gate: dry-run for $repo"
  if [ "$project_rel" = "." ]; then
    echo "  project-root: . (repo root)"
  else
    echo "  project-root: $project_rel (resolved from repo root)"
  fi
  echo "  HEAD: $head_now"
  echo "  base: $base_ref"
  echo "  parallelism: $parallelism"
  echo "  producers, in order:"
  producers_desc | sed 's/^/    - /'
  exit 0
fi

# --- per-repo integration lock ------------------------------------------
# Same lock file/convention as `worktree-extend.sh integrate`
# (<repo>/.git/autobuilder-integrate.lock via flock), so a gate run and an
# integrate on the same crate — or two gate runs — never overlap.
#
# PRD-extend-gate-lock-cloexec (2026-09-05 incident class): every producer
# subshell below closes fd 9 (`9>&-`) before exec'ing its child. Without
# this, a child that outlives the script — cargo autostarting the
# long-lived sccache daemon, or mcphost's bwrap warm-pool sandboxes leaking
# past `cargo test` — inherits fd 9 and keeps the lock held after this
# script exits, timing out the NEXT gate run (exit 4, $EXTEND_GATE_PRODUCER_LOCK_WAIT
# wait) even though the process that opened the lock is long gone. Do not
# remove the `9>&-` from a producer invocation without re-reading this
# comment.
lockfile="$repo/.git/autobuilder-integrate.lock"
exec 9>"$lockfile"
# PRD-build-extend-gate-concurrent-isolation requirement 8 (P2, journal
# visibility): every run records how long it waited for producer access —
# 0 when uncontended — so a future lane-status-style summary can tell
# whether the ≤5 same-target sub-cap is actually causing gate contention
# in practice.
lock_wait_t0=$(date +%s)
if ! flock -w "$EXTEND_GATE_PRODUCER_LOCK_WAIT" 9; then
  # PRD-build-extend-gate-concurrent-isolation requirement 2: fail closed
  # with an unambiguous, actionable message naming the contending PID —
  # never proceed to read (or start writing into) a receipts dir another
  # invocation may be mid-write on. `fuser` names every PID holding an
  # open fd on the lock file; the holder that actually has it flock'd is
  # normally the sole result, but a race (holder just exited) can leave
  # none — "unknown" rather than a misleading blank in that case.
  holder_pid="$(fuser "$lockfile" 2>/dev/null | tr -s ' \t' '\n' | grep -E '^[0-9]+$' | paste -sd, -)"
  die 4 "producer-lock-contended, pid=${holder_pid:-unknown} (could not acquire integration lock for $repo within ${EXTEND_GATE_PRODUCER_LOCK_WAIT}s — another integrate/gate is running)"
fi
lock_wait=$(( $(date +%s) - lock_wait_t0 ))

# --- prune landed worktrees before producing receipts (PRD-build-worktree-targets-off-root) --
# A gate must never start on a disk full of worktrees whose branches already
# landed on origin/main (two truth-tier measure runs died to ENOSPC on
# 2026-09-08 from exactly this). Best-effort: a missing worktree-extend.sh or
# a prune failure never blocks the gate itself.
WORKTREE_EXTEND="$BUILD_SCRIPTS/worktree-extend.sh"
[ -x "$WORKTREE_EXTEND" ] && "$WORKTREE_EXTEND" prune-landed "$repo" >&2

# --- refuse a dirty tree before any producer runs (AC2) ------------------
if [ -n "$(git -C "$repo" status --porcelain)" ]; then
  die 3 "refusing — working tree at $repo is dirty"
fi

# --- refuse a --head that doesn't match actual HEAD, before any producer
#     runs (AC3) --------------------------------------------------------
if [ -n "$head_want" ] && [ "$head_want" != "$head_now" ]; then
  die 5 "refusing — HEAD is $head_now, --head asked for $head_want"
fi

# --- verdict cache (PRD-build-gate-delta-baseline P1) --------------------
# Keyed on (HEAD sha, this script's own sha256) so an edit to extend-gate.sh
# itself (a new producer, a bugfix) always invalidates a stale cached
# verdict even at an unchanged HEAD. `--record-baseline` always runs the
# full sequence (a recording must reflect a fresh run, never a cache);
# `--force` always bypasses the cache. A cache hit never regenerates
# receipts and never re-takes the integration lock's expensive path —
# checked here, after the (cheap) dirty-tree/head-mismatch refusals above,
# so those refusals still apply to a would-be cache hit exactly as they do
# to a full run.
self_hash="$(sha256sum "$0" 2>/dev/null | awk '{print $1}')"
cache_file="$project_abs/target/autobuilder/last-verdict.json"
if ! $record_baseline && ! $force && [ -f "$cache_file" ]; then
  cached_head="$(jq -r '.head_sha // empty' "$cache_file" 2>/dev/null || true)"
  cached_hash="$(jq -r '.script_sha256 // empty' "$cache_file" 2>/dev/null || true)"
  if [ -n "$cached_head" ] && [ "$cached_head" = "$head_now" ] && [ -n "$cached_hash" ] && [ "$cached_hash" = "$self_hash" ]; then
    cached_verdict="$(jq -r '.verdict // empty' "$cache_file" 2>/dev/null || true)"
    cached_rc="$(jq -r '.exit_code // empty' "$cache_file" 2>/dev/null || true)"
    if [ -n "$cached_verdict" ] && [ -n "$cached_rc" ]; then
      echo "extend-gate: verdict=$cached_verdict (cached)"
      exit "$cached_rc"
    fi
  fi
fi

t0=$(date +%s)
blocking_notes=()
note_block() { blocking_notes+=("$1"); echo "extend-gate: $1" >&2; }

echo "extend-gate: $repo head=$head_now base=$base_ref parallelism=$parallelism"
if [ "$project_rel" = "." ]; then
  echo "extend-gate: project-root: . (repo root)"
else
  echo "extend-gate: project-root: $project_rel (resolved from repo root)"
fi

# 1. audit.sh, when the crate has one. Feeds the risk-gate receipt; a
#    non-zero exit here is logged but does not abort the run — the final
#    `autobuilder gate` is authoritative (see file header).
if [ -x "$repo/scripts/audit.sh" ]; then
  ( cd "$repo" && ./scripts/audit.sh ) 9>&- || note_block "risk-gate — scripts/audit.sh exited non-zero (see risk-gate receipt for detail)"
else
  echo "extend-gate: no scripts/audit.sh in $repo — skipping"
fi

# 2. intake — validates agent/intent-card.json against the schema and,
#    with --project, writes target/autobuilder/receipts/intake.json fresh
#    at HEAD. Before PRD-build-gate-producers, nothing in this sequence
#    ever passed --project, so intake.json was never regenerated by a
#    live gate run (intake.rs's own doc comment: validate-only "leaves no
#    files behind"). A repo with no agent/intent-card.json fails here
#    loudly, same as any other producer given a missing/invalid input —
#    no silent no-op.
( cd "$repo" && autobuilder intake --validate agent/intent-card.json --project "$project_rel" ) 9>&- \
  || note_block "intake — autobuilder intake exited non-zero (schema violation in agent/intent-card.json, missing file, or receipt write failure — see output above)"

# 3. proof receipt + session trace. Budgeted (PRD-build-cargo-concurrency-
#    budget): this producer shells to `cargo test`/`cargo build` internally,
#    so the whole phase takes one cargo-budget slot rather than racing every
#    other budgeted cargo caller on the host.
( cd "$repo" && cargo_budgeted autobuilder loop --project "$project_rel" --iteration 0 --head-sha "$head_now" --trace ) 9>&- \
  || note_block "proof-receipt — autobuilder loop --iteration 0 exited non-zero"

# 4. vti-plan.
( cd "$repo" && autobuilder vti-plan --project "$project_rel" --base "$base_ref" ) 9>&- \
  || note_block "vti-plan — autobuilder vti-plan exited non-zero"

# 5. rollback-plan over <base>..HEAD.
( cd "$repo" && autobuilder rollback-plan --project "$project_rel" --base "$base_ref" ) 9>&- \
  || note_block "rollback-plan — commits since $base_ref are not all revert-clean (see target/autobuilder/rollback.md); fix forward, or a human rewrites history and says so — this script never edits history to force a pass"

# 6. reviewer-agent: prepare, spawn the independent review headlessly via
#    `claude -p --model sonnet` (same tier /rustbuild routes it to; the
#    autobuilder binary cannot spawn a Claude subagent itself), finalize.
run_reviewer() {
  ( cd "$repo" && autobuilder reviewer-agent prepare --project "$project_rel" --base "$base_ref" ) 9>&- \
    || { note_block "reviewer-agent — prepare exited non-zero"; return 1; }
  local req="$project_abs/target/autobuilder/review-request.json"
  [ -f "$req" ] || { note_block "reviewer-agent — prepare did not write $req"; return 1; }
  command -v claude >/dev/null 2>&1 \
    || { note_block "reviewer-agent — claude CLI not on \$PATH (needed to spawn the independent review subagent)"; return 1; }
  [ -f "$REVIEWER_PROMPT" ] \
    || { note_block "reviewer-agent — missing prompt $REVIEWER_PROMPT"; return 1; }

  local out="$project_abs/target/autobuilder/review-output.json"
  local raw="$project_abs/target/autobuilder/review-output.raw.txt"
  local prompt
  prompt="$(cat "$REVIEWER_PROMPT")
---
Below is this review's target/autobuilder/review-request.json. The repo is
checked out at HEAD $head_now at $repo — read whatever you need under it.
$(cat "$req")
---
Reply with ONLY one JSON object, no prose, no markdown fences, matching
schema autobuilder.reviewer_agent_receipt.v1:
{\"schema\":\"autobuilder.reviewer_agent_receipt.v1\",\"head_sha\":\"...\",\"intent_card_sha\":\"...\",\"decision\":\"pass|concern|block\",\"block_reasons\":[...],\"concern_reasons\":[{\"id\":\"...\",\"note\":\"...\"}],\"falsification\":{\"test_audit\":\"...\",\"panic_audit\":\"...\",\"unsafe_audit\":\"...\",\"public_api_audit\":\"...\",\"deps_audit\":\"...\",\"drift_audit\":\"...\",\"counter_attack\":{\"description\":\"...\",\"test_skeleton\":\"...\"}}}"

  if ! ( cd "$repo" && claude -p "$prompt" --model sonnet --permission-mode bypassPermissions --output-format text ) 9>&- >"$raw" 2>"$raw.err"; then
    note_block "reviewer-agent — claude -p subagent invocation failed (see $raw.err)"
    return 1
  fi
  if ! python3 -c "
import json, re, sys
raw = open('$raw').read()
m = re.search(r'\{.*\}', raw, re.S)
if not m:
    sys.exit(1)
obj = json.loads(m.group(0))
json.dump(obj, open('$out', 'w'))
" 2>>"$raw.err"; then
    note_block "reviewer-agent — subagent did not return valid JSON (see $raw)"
    return 1
  fi
  ( cd "$repo" && autobuilder reviewer-agent finalize --project "$project_rel" --input "$out" ) 9>&- \
    || { note_block "reviewer-agent — finalize rejected the subagent's output"; return 1; }
}
run_reviewer || true

# 7. ci-checks — needs `gh` authenticated against the pushed HEAD.
if ! command -v gh >/dev/null 2>&1; then
  note_block "ci-checks — gh CLI not on \$PATH (install: https://cli.github.com)"
elif ! gh auth status >/dev/null 2>&1; then
  note_block "ci-checks — gh not authenticated: run 'gh auth login'"
else
  ( cd "$repo" && autobuilder ci-checks --project "$project_rel" ) 9>&- \
    || note_block "ci-checks — workflow(s) on HEAD are not green, or still pending (the next tick retries)"
fi

# 8. the 17 extended-gates producers, in parallel. Passed the RESOLVED
# project path (not $repo) so their receipts land in the same
# target/autobuilder/receipts/ the rest of this script's producers and
# the final `autobuilder gate` read from.
# subshell wraps the direct exec so 9>&- has a scope to apply to — this
# call is not otherwise inside a `( ... )` group.
# Budgeted as ONE phase (PRD-build-cargo-concurrency-budget): the internal
# $parallelism fan-out is exactly the "each branch/gate assumes it owns the
# box" pattern the 2026-09-09 OOM came from, so the whole extended-receipts
# run takes a single cargo-budget slot rather than each of its 17 producers
# racing every other budgeted cargo caller independently.
( cargo_budgeted "$RUSTBUILD_SCRIPTS/extended-receipts.sh" "$project_abs" "$parallelism" ) 9>&- \
  || note_block "extended-receipts — one or more extended producers did not pass|skip (see output above)"

# 9. the risk gate itself — authoritative pass/block, reads all 25 receipts.
gate_out="$(exec 9>&-; cd "$repo" && autobuilder gate --project "$project_rel" 2>&1)"
gate_rc=$?
printf '%s\n' "$gate_out"
summary="$(printf '%s\n' "$gate_out" | grep -m1 '^gate: ' || true)"

wall=$(( $(date +%s) - t0 ))
crate_name="$(basename "$repo")"
blockers_csv=""
if [ "${#blocking_notes[@]}" -gt 0 ]; then
  blockers_csv="$(IFS='|'; echo "${blocking_notes[*]}")"
fi
# Overridable so tests/ never writes into the real journal (default unchanged).
journal="${EXTEND_GATE_JOURNAL:-$HOME/brain/journal/build/$(date -u +%Y-%m-%d).md}"
mkdir -p "$(dirname "$journal")"

# --- record-baseline: write agent/gate-baseline.json from THIS run's
# blocking set, print it, done. Never computes or acts on a delta verdict
# — recording and shipping are separate, deliberate acts (design note:
# "the gate never auto-widens a baseline"). ---------------------------
gate_out_file="$(mktemp "${TMPDIR:-/tmp}/extend-gate-out.XXXXXX")"
printf '%s\n' "$gate_out" > "$gate_out_file"

if $record_baseline; then
  recorded="$("$GATE_DELTA" record "$repo" "$gate_out_file")" || { rm -f "$gate_out_file"; die 2 "gate-delta.sh record failed"; }
  rm -f "$gate_out_file"
  echo "extend-gate: recorded baseline to $repo/agent/gate-baseline.json"
  printf '%s\n' "$recorded"
  printf '%s  gate  %s  record-baseline  (head=%s base=%s %s wall=%ss lock_wait=%ss)\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$crate_name" "$head_now" "$base_ref" \
    "${summary:-gate: no-summary-line}" "$wall" "$lock_wait" >>"$journal"
  exit 0
fi

# --- delta verdict against the committed baseline (PRD-build-gate-delta-baseline) ---
# `gate-delta.sh verdict`'s own exit code already mirrors <gate_rc>
# byte-for-byte whenever there is no committed baseline (see that
# script's header) — using it unconditionally as this script's final
# exit code is what makes the absent-baseline path identical to the
# pre-this-PRD behavior. Only the PRESENT-baseline path prints or
# journals anything new.
delta_out="$("$GATE_DELTA" verdict "$repo" "$gate_out_file" "$gate_rc")"
delta_rc=$?
rm -f "$gate_out_file"
baseline_state="$(printf '%s\n' "$delta_out" | sed -n 's/^baseline=//p')"
delta_verdict="$(printf '%s\n' "$delta_out" | sed -n 's/^verdict=//p')"
new_blocks="$(printf '%s\n' "$delta_out" | sed -n 's/^new_blocks=//p')"
inherited_blocks="$(printf '%s\n' "$delta_out" | sed -n 's/^inherited_blocks=//p')"

final_rc="$delta_rc"
outcome="pass"; [ "$gate_rc" -eq 0 ] || outcome="block"
journal_suffix=""
if [ "$baseline_state" = "present" ]; then
  echo "extend-gate: delta verdict=$delta_verdict baseline=present new_blocks=${new_blocks:-none} inherited_blocks=${inherited_blocks:-none}"
  outcome="$delta_verdict"
  journal_suffix=" verdict=$delta_verdict inherited_blocks=[${inherited_blocks}]"
fi

# One journal line per gate run (requirement 8 / AC13): crate, HEAD, base
# tag, pass/block counts, blocking receipt names, wall seconds, and (PRD-
# build-extend-gate-concurrent-isolation requirement 8 / P2) how long this
# run waited for producer access before it started (0 when uncontended).
printf '%s  gate  %s  %s  (head=%s base=%s %s blocking=%s wall=%ss lock_wait=%ss)%s\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$crate_name" "$outcome" "$head_now" "$base_ref" \
  "${summary:-gate: no-summary-line}" "${blockers_csv:-none}" "$wall" "$lock_wait" "$journal_suffix" >>"$journal"

# --- write the verdict cache (P1) — every full run, pass/delta-pass/block
# alike, so a repeat invocation at the same head + same script replays
# instead of regenerating. ------------------------------------------------
cache_verdict_val="$outcome"
mkdir -p "$(dirname "$cache_file")"
jq -n --arg head "$head_now" --arg hash "$self_hash" --arg verdict "$cache_verdict_val" \
     --argjson rc "$final_rc" --arg new "$new_blocks" --arg inh "$inherited_blocks" '
  {
    head_sha: $head,
    script_sha256: $hash,
    verdict: $verdict,
    exit_code: $rc,
    new_blocks: ($new | if . == "" then [] else split(",") end),
    inherited_blocks: ($inh | if . == "" then [] else split(",") end)
  }
' > "$cache_file" 2>/dev/null || true

exit "$final_rc"
