#!/usr/bin/env bash
# extend-gate.sh — regenerate autobuilder's 25 receipts at HEAD on a
# rust-extend crate's main checkout, so the deploy gate a rust-extend ship
# reads is never bound to a stale commit. PRD-build-extend-gate-receipts.
#
# usage: extend-gate.sh <build_into> [--base <tag>] [--head <sha>] [--dry-run]
#                        [--project-root <rel>]
#                        [--parallelism N] [--record-baseline] [--force]
#                        [--phases-json]
#
# Phase timing (PRD-build-gate-phase-timing): every producer step below is
# individually timed (never restructured — same order, same pass/block
# contribution). The journal line's `wall=<s>s` gains a
# `phases=<name>:<s>,...` field right after it, in invocation order; a step
# this run never invoked (no scripts/audit.sh, gh unavailable, reviewer
# bypassed by a prior block) reads `<name>:skip`, and a step whose own
# subprocess exited non-zero reads `<name>:<s>!` — never a silent `:0`. The
# same breakdown, plus `wall_s` and `head`, lands in the cached verdict
# receipt (target/autobuilder/last-verdict.json) under a `phases` key.
# `--phases-json` is a read-only mode: prints that cached `{phases,
# wall_s, head}` for <build_into>'s last gate and exits 0 — no producer
# runs, no lock taken, nothing journaled. `--print-verdict-path`
# (PRD-build-gate-before-land requirement 3) is the same read-only class:
# resolves and prints the verdict-cache path (the exact
# target/autobuilder/last-verdict.json a real run at <build_into> would
# read/write, honoring --project-root / find_cargo_root the same way) and
# exits 0 — the rebase-and-regate loop's way of locating the file to pass
# as `worktree-extend.sh land --verdict <path>` without duplicating the
# project-root search.
#
# On a clean main checkout, at HEAD, in this order:
#   scripts/audit.sh                         (if the crate has one)
#   autobuilder intake --validate agent/intent-card.json --project <root>
#     (writes receipts/intake.json fresh at HEAD — PRD-build-gate-producers;
#     before that PRD, nothing in this sequence ever passed --project, so
#     intake.json was never regenerated by a live gate run)
#   autobuilder loop --project <root> --iteration 0 --head-sha <HEAD> --trace
#   autobuilder vti-plan
#   autobuilder rollback-plan --base <base>
#   autobuilder reviewer-agent prepare --base <base>, then finalize
#     (the binary cannot spawn its own subagent — see
#     autobuilder/src/reviewer.rs — so this script spawns a headless
#     sonnet review via `claude -p` and feeds its JSON to finalize)
#   autobuilder ci-checks
#   ~/.claude/skills/rustbuild/scripts/extended-receipts.sh <root> [parallelism]
#   autobuilder gate --project <root>
# <root> is normally <build_into> itself, but is resolved to the nearest
# subdirectory containing Cargo.toml when <build_into> has none at its own
# root (see "cargo project root resolution" below).
# <base> defaults to the newest `v<major>.<minor>.<patch>` tag reachable
# from HEAD by first-parent (autobuilder's own rollback-plan convention),
# falling back to the crate's initial commit when no such tag exists.
#
# Prints the gate's own summary line (`gate: head=... pass=N block=M
# verdict=...`) and exits with the gate's verdict.
#
# Delta verdict against a committed baseline (PRD-build-gate-delta-baseline).
# `autobuilder gate`'s own pass/block is not the final word: this script
# additionally diffs the blocking receipt set against
# `<build_into>/agent/gate-baseline.json` AT HEAD (a working-tree-only copy
# never counts — fail closed) via `scripts/gate-delta.sh verdict`, and
# prints its own summary line:
#   extend-gate: delta verdict=pass|delta-pass|block baseline=present|absent new_blocks=<...> inherited_blocks=<...>
# `delta-pass` means block>0 but every blocking receipt name is already in
# the baseline — this script then exits 0 (shippable), same as a plain
# `pass`. `block` means at least one blocking receipt is NOT in the
# baseline (or there is no committed baseline at all — today's behavior,
# preserved byte-for-byte: no baseline means this new summary line and the
# exit code are unaffected by anything above). `--record-baseline` writes
# the baseline from the CURRENT run's blocking set instead of computing a
# verdict against one — see that flag's own note below. A verdict run
# never writes or widens the baseline itself.
#
# <build_into> is normally both the git repo root and the Cargo project
# root (mcphost, wm-node, adopt) — but that's not universal. When the repo
# root has no Cargo.toml (rustbuild's has always lived one level down, at
# autobuilder/Cargo.toml), immediate subdirectories are searched (depth 1,
# then depth 2 if depth 1 finds nothing — never descending into target/ or
# .git/) for exactly one Cargo.toml, and THAT resolved path is passed to
# every producer below (including extended-receipts.sh's 17) instead of
# the repo root, so cargo-invoking producers stop exiting 101 for "could
# not find Cargo.toml" against a directory that was never the actual
# crate. A repo with a root Cargo.toml AND a nested one keeps the root,
# unchanged (no search triggered). Ambiguous (>1 candidate) or absent (0
# candidates) fails loudly (exit 6) naming what was searched, before any
# producer runs — never a silent 101. PRD-build-extend-gate-nested-crate-project.
#
# Exit codes:
#   0  gate verdict pass (pass=25 block=0) OR delta-pass (block>0 but every
#      blocking receipt is in the committed baseline) OR a successful
#      `--record-baseline` write (that mode's exit code reports the write,
#      not the underlying pass/block)
#   1  gate verdict block (one or more receipts failed, and at least one
#      of them is not in the committed baseline — or there is no committed
#      baseline at all)
#   1  usage error (bad/missing arguments)
#   2  a required binary is missing from $PATH (autobuilder, extended-receipts.sh,
#      ship-tag.sh, gate-delta.sh, jq) — cannot even attempt a run
#   3  dirty tree — refused before any producer ran, nothing under
#      target/autobuilder/ changed
#   4  could not acquire the per-repo integration lock within
#      $EXTEND_GATE_PRODUCER_LOCK_WAIT seconds (default 90 — PRD-build-
#      extend-gate-concurrent-isolation requirement 2). The message names
#      the contending pid(s) ("producer-lock-contended, pid=<n>[,<n>...]"),
#      is refused before any producer ran, and never emits a `gate: ...
#      pass=.../block=...` verdict line — fail-closed, not fail-wrong.
#   5  --head <sha> does not match actual HEAD — refused before any
#      producer ran
#   6  could not resolve a unique Cargo project root under <build_into>
#      (none found, or more than one candidate) — refused before any
#      producer ran
#   7  installed `autobuilder` binary is STALE — its `--version` is older
#      than the canonical crate's `[package] version` in
#      $AUTOBUILDER_CANONICAL_CARGO_TOML — refused before any producer ran
#      (AC4, PRD-autobuilder-source-unify). The message names the
#      installed version, the expected (canonical) version, and the exact
#      `cargo install --path <canonical-crate-dir> --locked` fix. Skipped
#      (not an error) when the canonical Cargo.toml itself is absent —
#      e.g. a test HOME with no checked-out canonical crate — since this
#      guard is about staleness, not about requiring the canonical source
#      to exist on every box that runs a gate.
#
# --record-baseline: runs the full producer sequence exactly as a normal
# invocation, then instead of computing a delta verdict, writes
# `<build_into>/agent/gate-baseline.json` from THIS run's blocking receipt
# set (`scripts/gate-delta.sh record`) and prints the recorded document.
# Meant to be committed by the caller (a human, or an explicit gate-debt
# PRD) — this script never commits, and a plain verdict run never widens
# or auto-records a baseline on its own. Bypasses the verdict cache below
# (a recording always reflects a fresh run). Exits 0 on a successful
# write regardless of the underlying pass/block count.
#
# Verdict cache: on a successful (non-dry-run, non-record-baseline) run,
# the computed verdict is cached at
# `<project>/target/autobuilder/last-verdict.json` keyed on (HEAD sha,
# this script's own sha256). A later invocation at the SAME head with an
# UNCHANGED script replays the cached verdict (`extend-gate: verdict=...
# (cached)`, same exit code) instead of regenerating all 25 receipts.
# `--force` bypasses the cache and always runs the full sequence.
#
# Never runs `cargo clean` in the crate's own target/ (determinism and
# cold-build-time already build in their own temp target dirs — memory
# rule: never `cargo clean` a crate with receipts).
#
# Takes the SAME per-repo integration lock `worktree-extend.sh integrate`
# takes (`<repo>/.git/autobuilder-integrate.lock`, `flock`), held from
# BEFORE the first producer runs (scripts/audit.sh) through the final
# `autobuilder gate` accounting step, so two PRDs landing on one crate in
# one tick — or N concurrent gate invocations dispatched against one
# shared build_into in the same tick, PRD-build-extend-gate-concurrent-
# isolation — never run producers concurrently: the second (and every
# subsequent) run waits for the lock, then regenerates receipts at the
# HEAD it sees once it acquires it (the later HEAD, if one landed in the
# meantime). A run that cannot acquire the lock within
# $EXTEND_GATE_PRODUCER_LOCK_WAIT seconds (default 90) fails closed — see
# exit code 4 below — rather than ever reading a receipt set another
# invocation may still be mid-write on.
#
# --dry-run prints the producer sequence, the resolved base tag, and HEAD;
# writes nothing under target/autobuilder/; never takes the lock; exits 0.
#
# Individual producer steps are run best-effort: a non-zero exit from any
# one of them (rollback-plan finding a non-revert-clean merge, ci-checks
# finding a red workflow, ...) is logged and the run CONTINUES through the
# rest of the sequence, so every receipt gets regenerated at HEAD and the
# final `autobuilder gate` is the single source of truth for pass/block —
# an early abort would leave the receipt set partial and mislead the next
# tick about which check actually failed. Per requirement 7 (resumable): a
# tick that ends mid-gate leaves a partial receipt set, which is never
# read as green; the next tick reruns this script from the start.
set -uo pipefail
BUILD_SCRIPTS="$(cd "$(dirname "$0")" && pwd)"

# --- PATH order guard (P0 requirement 1, PRD-build-gate-cargo-route-attest) --
# Previously this unconditionally prepended the real cargo/local-bin dirs
# ahead of whatever $PATH the caller armed, silently shadowing the
# burst-lane shim (scripts/burst-lane-bin/cargo) even when a caller had
# already exported it first per SKILL.md's "mixed-tick burst routing"
# section — the root cause of 53 autobuilder loops + 34 gate `cargo test`
# runs all landing on RedBaron on 2026-09-10 while casper sat idle at 3%
# utilization for EUR9.59. Now: $HOME/.cargo/bin and $HOME/.local/bin are
# APPENDED (never prepended), so any shim directory the caller already
# armed ahead of them on $PATH stays ahead. If BURST_LANE=1 and NEITHER
# shim directory (burst-lane-bin, cargo-budget-bin) is already anywhere on
# the inherited $PATH, this script arms burst-lane-bin itself, so a caller
# that merely sets BURST_LANE=1 without separately exporting $PATH still
# routes (AC1) — it does not reorder an already-present-but-shadowed shim
# (see the route-check call below for that case; requirement 1 is a guard
# against re-shadowing, not a guarantee of correct ordering the caller
# already got wrong). The resolved cargo path is logged once, right here,
# before any producer — before even repo validation — runs.
_extend_gate_path_has_dir() {  # $1=dir -> rc0 if present on $PATH (resolved, order-independent)
  local want resolved d saved_ifs
  want="$(cd "$1" 2>/dev/null && pwd -P || true)"
  [ -n "$want" ] || return 1
  saved_ifs="$IFS"; IFS=:
  for d in $PATH; do
    IFS="$saved_ifs"
    [ -n "$d" ] || continue
    resolved="$(cd "$d" 2>/dev/null && pwd -P || true)"
    if [ "$resolved" = "$want" ]; then IFS="$saved_ifs"; return 0; fi
  done
  IFS="$saved_ifs"
  return 1
}
if [ "${BURST_LANE:-0}" = "1" ] \
   && ! _extend_gate_path_has_dir "$BUILD_SCRIPTS/burst-lane-bin" \
   && ! _extend_gate_path_has_dir "$BUILD_SCRIPTS/cargo-budget-bin"; then
  export PATH="$BUILD_SCRIPTS/burst-lane-bin:$PATH"
fi
export PATH="$PATH:$HOME/.cargo/bin:$HOME/.local/bin"
unset -f _extend_gate_path_has_dir
_extend_gate_resolved_cargo="$(command -v cargo 2>/dev/null || true)"
echo "extend-gate: cargo=${_extend_gate_resolved_cargo:-not-found}"

# Overridable so tests/ can point at a fixture dir of fake binaries
# without touching production behavior (default unchanged).
RUSTBUILD_SCRIPTS="${RUSTBUILD_SCRIPTS:-$HOME/.claude/skills/rustbuild/scripts}"
REVIEWER_PROMPT="${REVIEWER_PROMPT:-$HOME/.claude/skills/rustbuild/prompts/reviewer-agent.md}"
# Canonical autobuilder crate Cargo.toml — the install-freshness guard
# (AC4, PRD-autobuilder-source-unify, exit 7 below) reads its
# `[package] version` and compares it to the installed `autobuilder
# --version`. Overridable so tests/ can point at a fixture Cargo.toml
# without touching production behavior (default unchanged: the split
# repo's nested crate root, matching this fleet's `--project-root
# autobuilder` convention).
AUTOBUILDER_CANONICAL_CARGO_TOML="${AUTOBUILDER_CANONICAL_CARGO_TOML:-$HOME/wintermute/autobuilder/autobuilder/Cargo.toml}"
GATE_DELTA="$BUILD_SCRIPTS/gate-delta.sh"
# PRD-build-gate-debt-auto-prd requirement 1: attribute each blocking
# finding as in-scope (the building PRD's own diff) or inherited (landed
# by another PRD's merge). Overridable so tests/ can point at a fixture
# without touching production behavior (default unchanged).
GATE_ATTRIBUTION="${GATE_ATTRIBUTION:-$BUILD_SCRIPTS/gate-attribution.sh}"
# Three-state retrofit (PRD-build-three-state-probes): fail-open sourcing so
# an unshipped/missing library never breaks a gate run.
if [ -r "$BUILD_SCRIPTS/probe-result.sh" ]; then
  # shellcheck source=probe-result.sh
  source "$BUILD_SCRIPTS/probe-result.sh"
else
  probe_emit() { :; }
fi
# PRD-build-cargo-concurrency-budget: every producer step below that shells
# to cargo (the proof-receipt loop and the 17 extended producers) takes a
# budget slot for its whole phase instead of assuming it owns the host —
# see cargo-budget.sh's header for why (RedBaron OOMed for ~6min at
# load 21,466 on 2026-09-09 with the sub-cap at 3). Overridable so tests/
# can point at a fixture wrapper without touching production behavior.
CARGO_BUDGET="${CARGO_BUDGET:-$BUILD_SCRIPTS/cargo-budget.sh}"
# PRD-build-extend-gate-concurrent-isolation: the producer-lock wait below
# (requirement 2 — bounded wait, explicit fail-closed) is its own ceiling,
# distinct from worktree-extend.sh integrate's own ~120s wait on the SAME
# lock file and from manifest-set.sh's unrelated 60s manifest-write
# ceiling — overridable so a selftest can force contention/timeout in
# seconds instead of minutes without touching production behavior
# (default unchanged in spirit, just named and shortened from the prior
# unconditional 120 to the PRD's specified 90).
EXTEND_GATE_PRODUCER_LOCK_WAIT="${EXTEND_GATE_PRODUCER_LOCK_WAIT:-90}"
# PRD-build-burst-pull-on-demand requirement 2: this IS the gate harness's
# own local-cargo choke point (cargo-budget.sh is a local concurrency cap,
# never a remote route). A burst-lane `run` elsewhere may have left
# $repo's target/ remote-dirty in the meantime; overridable so tests/ can
# point at a fixture without touching production behavior.
BURST_LANE_SH="${BURST_LANE_SH:-$BUILD_SCRIPTS/burst-lane.sh}"
# PRD-build-cargo-budget-per-invocation requirement 7: the proof-receipt
# loop's `autobuilder loop` step runs under gate-wedge.sh so a producer
# idle for EXTEND_GATE_LOOP_WALL_S (default 1800s) is killed and the gate
# blocks instead of holding the gate (and, pre-this-PRD, a whole cargo-
# budget slot) for an hour and then blocking anyway. Overridable so
# tests/ can point at a fixture / shrink the wall without touching
# production behavior.
GATE_WEDGE_SH="${GATE_WEDGE_SH:-$BUILD_SCRIPTS/gate-wedge.sh}"
EXTEND_GATE_LOOP_WALL_S="${EXTEND_GATE_LOOP_WALL_S:-1800}"
GATE_WEDGE_STATE_DIR="${GATE_WEDGE_STATE_DIR:-$BUILD_SCRIPTS/../state/gate-wedge}"
cargo_budgeted() {
  # Retained for any DIRECT `cargo test`/`clippy`/`deny` call this gate
  # makes itself (none today — see run_unslotted_producer() below for
  # where the two producer-phase call sites moved to,
  # PRD-build-cargo-budget-per-invocation requirement 1). Fails open
  # (never blocks the gate) if burst-lane.sh or cargo-budget.sh is
  # missing — this gate must still run against whatever is on disk
  # rather than turn a missing helper into a gate outage.
  if [ -x "$BURST_LANE_SH" ]; then
    "$BURST_LANE_SH" ensure-fresh "$repo" >/dev/null 2>&1 || true
  fi
  if [ -x "$CARGO_BUDGET" ]; then
    "$CARGO_BUDGET" run -- "$@"
  else
    "$@"
  fi
}
# PRD-build-cargo-budget-per-invocation requirement 1: a producer phase
# (the proof-receipt loop's `autobuilder loop`, extended-receipts.sh's 17
# producers) no longer takes ONE cargo-budget slot for its whole phase —
# that let an agent-driven, mostly-idle phase hold a slot for up to an
# hour (the 2026-09-13 incident: one hold at peak_load=0.83, no compiler
# running, while 20 other cargo invocations elsewhere timed out on the 2
# slots this budgets). Instead the producer runs UNSLOTTED, with
# cargo-budget-bin FIRST on $PATH (so every real `cargo test`/`clippy`/
# `deny`/`nextest`/`build --release` call it shells to takes its own slot
# for exactly its own duration — see cargo-budget.sh) and
# CARGO_BUDGET_PARENT_STEP set so each of those slots' ledger rows records
# which producer spawned it. The `VAR=val PATH=... cmd` prefix form here
# scopes both to this one command's own process tree — it never mutates
# this script's own $PATH/env for any later phase.
CARGO_BUDGET_BIN_DIR="${CARGO_BUDGET_BIN_DIR:-$BUILD_SCRIPTS/cargo-budget-bin}"
run_unslotted_producer() {  # $1=parent-step name, then the producer command
  local step="$1"; shift
  if [ -x "$BURST_LANE_SH" ]; then
    "$BURST_LANE_SH" ensure-fresh "$repo" >/dev/null 2>&1 || true
  fi
  PATH="$CARGO_BUDGET_BIN_DIR:$PATH" CARGO_BUDGET_PARENT_STEP="$step" "$@"
}

die() { echo "extend-gate: $2" >&2; exit "$1"; }

usage() {
  cat <<'EOF'
usage: extend-gate.sh <build_into> [--base <tag>] [--head <sha>] [--dry-run]
                       [--parallelism N] [--record-baseline] [--force]
                       [--phases-json] [--print-verdict-path]
                       [--scope main|branch --slug <slug>]
EOF
}

producers_desc() {
  cat <<'EOF'
scripts/audit.sh (if present)
autobuilder intake --validate agent/intent-card.json --project <root>
autobuilder loop --project <root> --iteration 0 --head-sha <HEAD> --trace
autobuilder vti-plan
autobuilder rollback-plan --base <base>
autobuilder reviewer-agent prepare --base <base> ; claude -p (headless sonnet review) ; autobuilder reviewer-agent finalize
autobuilder ci-checks
extended-receipts.sh <root> [parallelism]  (17 extended producers)
autobuilder gate --project <root>
EOF
}

[ $# -ge 1 ] || { usage >&2; exit 1; }
case "$1" in -h|--help) usage; exit 0 ;; esac
repo_arg="$1"; shift

base_override=""
head_want=""
dry_run=false
parallelism=6
record_baseline=false
force=false
project_root_override=""
phases_json_mode=false
print_verdict_path_mode=false
# PRD-build-gate-before-land requirement 1 (P0): a branch-scoped gate runs
# the full producer sequence inside a worktree, under a per-branch lock,
# instead of the shared per-crate `autobuilder-integrate.lock` — so N
# siblings on the same crate can gate concurrently with lock_wait=0s.
# `--scope main` (the default, and the only value before this PRD) is
# byte-identical to prior behavior: same lockfile, same journal shape.
scope="main"
slug=""

while [ $# -gt 0 ]; do
  case "$1" in
    --base)             base_override="${2:?extend-gate: --base needs a value}"; shift 2 ;;
    --head)             head_want="${2:?extend-gate: --head needs a value}"; shift 2 ;;
    --dry-run)          dry_run=true; shift ;;
    --parallelism)      parallelism="${2:?extend-gate: --parallelism needs a value}"; shift 2 ;;
    --record-baseline)  record_baseline=true; shift ;;
    --force)            force=true; shift ;;
    --project-root)     project_root_override="${2:?extend-gate: --project-root needs a value}"; shift 2 ;;
    --phases-json)      phases_json_mode=true; shift ;;
    --print-verdict-path) print_verdict_path_mode=true; shift ;;
    --scope)            scope="${2:?extend-gate: --scope needs a value}"; shift 2 ;;
    --slug)             slug="${2:?extend-gate: --slug needs a value}"; shift 2 ;;
    *) die 1 "unknown argument: $1 (see --help)" ;;
  esac
done

case "$scope" in
  main|branch) : ;;
  *) die 1 "--scope must be 'main' or 'branch' (got: $scope)" ;;
esac
if [ "$scope" = branch ] && [ -z "$slug" ]; then
  die 1 "--scope branch requires --slug <slug>"
fi

repo="$(cd "$repo_arg" 2>/dev/null && pwd)" || die 1 "no such directory: $repo_arg"
git -C "$repo" rev-parse --git-dir >/dev/null 2>&1 || die 1 "not a git repo: $repo"
command -v autobuilder >/dev/null 2>&1 || die 2 "autobuilder not on \$PATH (cargo install --path ~/wintermute/rustbuild/autobuilder --locked)"
[ -x "$RUSTBUILD_SCRIPTS/extended-receipts.sh" ] || die 2 "missing $RUSTBUILD_SCRIPTS/extended-receipts.sh"
[ -x "$RUSTBUILD_SCRIPTS/ship-tag.sh" ] || die 2 "missing $RUSTBUILD_SCRIPTS/ship-tag.sh"
[ -x "$GATE_DELTA" ] || die 2 "missing $GATE_DELTA"
command -v jq >/dev/null 2>&1 || die 2 "jq not on \$PATH (needed by gate-delta.sh)"

# --- install-freshness guard (AC4, PRD-autobuilder-source-unify) --------
# The installed `autobuilder` binary is the tool every producer below
# shells out to (intake, loop, vti-plan, rollback-plan, reviewer-agent,
# ci-checks, gate) — ITS OWN crate version, not $repo's, is what matters
# here: a binary older than the canonical crate silently runs
# feature-incomplete checks (e.g. an old rollback model) and produces
# receipts that look green but aren't. Refused before any producer runs,
# and before the project-root search / integration lock below, since
# neither needs to happen for a run this guard is about to block anyway.
# See exit code 7 above for the absent-canonical-Cargo.toml skip case.
canonical_crate_version() {
  local toml="$1" in_pkg=0 line
  [ -f "$toml" ] || return 1
  while IFS= read -r line; do
    case "$line" in
      '[package]') in_pkg=1; continue ;;
      '['*)        in_pkg=0; continue ;;
    esac
    if [ "$in_pkg" -eq 1 ]; then
      case "$line" in
        version\ =\ \"*\"|version=\"*\")
          line="${line#*\"}"
          printf '%s\n' "${line%%\"*}"
          return 0
          ;;
      esac
    fi
  done < "$toml"
  return 1
}

version_lt() {
  [ "$1" = "$2" ] && return 1
  local lowest
  lowest="$(printf '%s\n%s\n' "$1" "$2" | sort -t. -k1,1n -k2,2n -k3,3n | head -1)"
  [ "$lowest" = "$1" ]
}

if canonical_version="$(canonical_crate_version "$AUTOBUILDER_CANONICAL_CARGO_TOML")" && [ -n "$canonical_version" ]; then
  installed_version="$(autobuilder --version 2>/dev/null | awk '{print $NF}')"
  if [ -z "$installed_version" ]; then
    probe_emit gate-receipt-freshness could-not-check "could not parse 'autobuilder --version' output (canonical expects $canonical_version)" >/dev/null
    die 2 "could not parse 'autobuilder --version' output to determine the installed version (canonical crate expects $canonical_version at $AUTOBUILDER_CANONICAL_CARGO_TOML)"
  fi
  if version_lt "$installed_version" "$canonical_version"; then
    probe_emit gate-receipt-freshness dirty "installed=$installed_version expected=$canonical_version — receipts about to be regenerated by a stale binary" >/dev/null
    canonical_dir="$(dirname "$AUTOBUILDER_CANONICAL_CARGO_TOML")"
    die 7 "installed autobuilder binary is STALE — installed=$installed_version expected=$canonical_version (canonical crate: $AUTOBUILDER_CANONICAL_CARGO_TOML) — fix: cargo install --path $canonical_dir --locked"
  fi
  probe_emit gate-receipt-freshness clean "installed=$installed_version expected=$canonical_version (fresh)" >/dev/null
else
  # Previously a bare informational echo — which reads exactly like the
  # PRD's silent-failure class: "the guard found nothing to block on" and
  # "the guard could not even determine whether to block" printed the same
  # shape (a skip line) and were indistinguishable downstream. Now recorded
  # explicitly as could-not-check rather than folded into an implicit clean.
  probe_emit gate-receipt-freshness could-not-check "no canonical crate Cargo.toml at $AUTOBUILDER_CANONICAL_CARGO_TOML" >/dev/null
  echo "extend-gate: no canonical crate Cargo.toml at $AUTOBUILDER_CANONICAL_CARGO_TOML — skipping install-freshness guard" >&2
fi

# --- cargo project root resolution (PRD-build-extend-gate-nested-crate-project) ---
# $repo itself wins immediately if it has a Cargo.toml (the common case,
# and the edge case of a repo with both a root AND a nested Cargo.toml —
# root wins, no search performed at all, so byte-identical behavior for
# every already-onboarded crate). Otherwise search one level down, then
# two, for exactly one Cargo.toml, skipping target/ and .git/ at every
# level. Prints the resolved path on success; prints a human-readable
# reason (ambiguous / absent, naming what was searched) on failure.
find_cargo_root() {
  local base="$1"
  if [ -f "$base/Cargo.toml" ]; then
    printf '%s\n' "$base"
    return 0
  fi
  local d b
  local -a d1=()
  for d in "$base"/*/; do
    [ -d "$d" ] || continue
    b="$(basename "$d")"
    case "$b" in target|.git) continue ;; esac
    [ -f "$d/Cargo.toml" ] && d1+=("${d%/}")
  done
  if [ "${#d1[@]}" -eq 1 ]; then
    printf '%s\n' "${d1[0]}"
    return 0
  elif [ "${#d1[@]}" -gt 1 ]; then
    # Disambiguate the common <repo>/<repo>/Cargo.toml nesting pattern: if
    # exactly one candidate's basename matches the repo's own basename,
    # prefer it over unrelated sibling dirs (e.g. a "tools/" cargo
    # workspace). Only fires inside this already-ambiguous branch, so
    # repos without this exact collision are unaffected.
    local base_name="$(basename "$base")" self_match="" self_count=0 cand
    for cand in "${d1[@]}"; do
      if [ "$(basename "$cand")" = "$base_name" ]; then
        self_match="$cand"
        self_count=$((self_count + 1))
      fi
    done
    if [ "$self_count" -eq 1 ]; then
      printf '%s\n' "$self_match"
      return 0
    fi
    printf 'ambiguous — multiple Cargo.toml found one level under %s: %s' "$base" "${d1[*]}"
    return 1
  fi
  local d1dir b1 d2dir b2
  local -a d2=()
  for d1dir in "$base"/*/; do
    [ -d "$d1dir" ] || continue
    b1="$(basename "$d1dir")"
    case "$b1" in target|.git) continue ;; esac
    for d2dir in "$d1dir"*/; do
      [ -d "$d2dir" ] || continue
      b2="$(basename "$d2dir")"
      case "$b2" in target|.git) continue ;; esac
      [ -f "$d2dir/Cargo.toml" ] && d2+=("${d2dir%/}")
    done
  done
  if [ "${#d2[@]}" -eq 1 ]; then
    printf '%s\n' "${d2[0]}"
    return 0
  elif [ "${#d2[@]}" -gt 1 ]; then
    # Same repo-basename tie-break as the one-level-down case, mirrored
    # for consistency (untested pattern — the one-level case above is the
    # one actually observed).
    local base_name2="$(basename "$base")" self_match2="" self_count2=0 cand2
    for cand2 in "${d2[@]}"; do
      if [ "$(basename "$cand2")" = "$base_name2" ]; then
        self_match2="$cand2"
        self_count2=$((self_count2 + 1))
      fi
    done
    if [ "$self_count2" -eq 1 ]; then
      printf '%s\n' "$self_match2"
      return 0
    fi
    printf 'ambiguous — multiple Cargo.toml found two levels under %s: %s' "$base" "${d2[*]}"
    return 1
  fi
  printf 'no Cargo.toml found at %s, in its immediate subdirectories, or two levels down (searched depth-1 and depth-2, excluding target/ and .git/)' "$base"
  return 1
}

# --project-root <rel>: explicit disambiguation when find_cargo_root's
# one-crate rule can't decide (e.g. sibling crates one level down, like
# autobuilder/ + tools/). Relative to the repo; must contain a Cargo.toml.
if [ -n "$project_root_override" ]; then
  project_abs="$repo/$project_root_override"
  [ -f "$project_abs/Cargo.toml" ] || die 6 "no Cargo.toml at --project-root $project_root_override (looked in $project_abs)"
else
  project_abs="$(find_cargo_root "$repo")" || die 6 "$project_abs"
fi
project_rel="$(realpath --relative-to="$repo" "$project_abs")"

# --- --phases-json (P1, PRD-build-gate-phase-timing requirement) ---------
# Prints the `phases` object (plus wall_s/head) from the last gate's cached
# verdict (target/autobuilder/last-verdict.json — the same file the verdict
# cache above reads/writes) for <build_into>. Read-only: never runs a
# producer, never takes the integration lock, never touches the journal.
# `{}` (exit 0) when no cached verdict exists yet, or it predates this PRD
# (no `phases` key) — a fresh repo or an old cache is a legitimate "nothing
# to report yet", not an error.
if $phases_json_mode; then
  phases_cache_file="$project_abs/target/autobuilder/last-verdict.json"
  if [ -f "$phases_cache_file" ]; then
    jq -c '{phases: (.phases // {}), wall_s: (.wall_s // null), head: (.head // .head_sha // null)}' "$phases_cache_file" 2>/dev/null \
      || echo '{"phases":{},"wall_s":null,"head":null}'
  else
    echo '{"phases":{},"wall_s":null,"head":null}'
  fi
  exit 0
fi

# --- --print-verdict-path (PRD-build-gate-before-land requirement 3) -----
# Prints the resolved verdict-cache path (target/autobuilder/last-verdict.json
# under the SAME project-root resolution a real run would use — repo root,
# or the --project-root override, or find_cargo_root's search) for <repo>
# and exits 0. Read-only, same class as --phases-json: no producer, no
# lock, no journal. Lets a caller (the rebase-and-regate loop) locate the
# exact file to pass as `land --verdict <path>` without re-implementing
# find_cargo_root's search itself.
if $print_verdict_path_mode; then
  echo "$project_abs/target/autobuilder/last-verdict.json"
  exit 0
fi

# --- base resolution ---------------------------------------------------
# Mirrors autobuilder rollback-plan's own default exactly (see
# autobuilder/src/rollback.rs newest_reachable_tag/resolve_default_base):
# walk first-parent history from HEAD backward, take the newest
# v<major>.<minor>.<patch> tag found; else the crate's initial commit.
# Computed here (not just left to rollback-plan's own default) so
# --dry-run can report it without running any producer, and so
# reviewer-agent prepare reviews the SAME range rollback-plan checks
# (user story 5: <last-tag>..HEAD, not a branch that no longer exists).
newest_reachable_tag() {
  local sha tags best
  while read -r sha; do
    [ -n "$sha" ] || continue
    tags="$(git -C "$repo" tag --points-at "$sha" 2>/dev/null | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || true)"
    [ -n "$tags" ] || continue
    best="$(printf '%s\n' $tags | sed 's/^v//' | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)"
    printf 'v%s\n' "$best"
    return 0
  done < <(git -C "$repo" rev-list --first-parent HEAD 2>/dev/null)
  return 1
}

resolve_base() {
  if [ -n "$base_override" ]; then
    printf '%s\n' "$base_override"
    return 0
  fi
  local t
  if t="$(newest_reachable_tag)"; then
    printf '%s\n' "$t"
    return 0
  fi
  git -C "$repo" rev-list --max-parents=0 HEAD 2>/dev/null | tail -1
}

# --- tag-lineage self-heal ----------------------------------------------
# 2026-09-09: parallel-integrate branch agents bumped 0.32.0-0.34.0 without
# tagging; one missing tag turned rollback-plan red for every sibling PRD
# sharing the repo. Tagging is bookkeeping on commits that already exist, so
# the gate repairs it deterministically instead of trusting agent prompts:
# walk first-parent from HEAD to the newest existing v-tag (bounded), and for
# every commit whose crate version changed, create + push the missing tag.
backfill_version_tags() {
  local manifest="$project_rel/Cargo.toml"
  [ "$project_rel" = "." ] && manifest="Cargo.toml"
  # The CURRENT version (what HEAD's Cargo.toml declares) is never backfilled:
  # the redeploy-tag producer owns placing it on the green HEAD. Backfill only
  # heals HISTORICAL lineage (versions already superseded by a later bump).
  local current_ver
  current_ver="$(git -C "$repo" show "HEAD:$manifest" 2>/dev/null | sed -n 's/^version *= *"\([0-9.]*\)".*/\1/p' | head -1)"
  local sha ver parent pver n=0
  while read -r sha; do
    n=$((n + 1)); [ "$n" -gt 100 ] && break
    # stop at the newest already-tagged commit — lineage below it is history
    if git -C "$repo" tag --points-at "$sha" 2>/dev/null | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
      [ "$n" -gt 1 ] && break
      continue
    fi
    ver="$(git -C "$repo" show "$sha:$manifest" 2>/dev/null | sed -n 's/^version *= *"\([0-9.]*\)".*/\1/p' | head -1)"
    [ -n "$ver" ] || continue
    parent="$(git -C "$repo" rev-parse "$sha^" 2>/dev/null)" || continue
    pver="$(git -C "$repo" show "$parent:$manifest" 2>/dev/null | sed -n 's/^version *= *"\([0-9.]*\)".*/\1/p' | head -1)"
    [ "$ver" = "$current_ver" ] && continue
    if [ "$ver" != "$pver" ] && ! git -C "$repo" rev-parse "v$ver" >/dev/null 2>&1; then
      git -C "$repo" tag "v$ver" "$sha" 2>/dev/null \
        && echo "extend-gate: tag-lineage self-heal — created v$ver at ${sha:0:9}" >&2 \
        && git -C "$repo" push origin "refs/tags/v$ver" >/dev/null 2>&1 || true
    fi
  done < <(git -C "$repo" rev-list --first-parent HEAD 2>/dev/null)
}
backfill_version_tags

# Executable "shipped" contract — hard enforcement point. backfill above heals
# the mechanical (tag) case; anything still failing is a real shipping defect.
if ! "$BUILD_SCRIPTS/ship-postconditions.sh" "$repo" --project-root "$project_rel"; then
  die 1 "ship-postconditions failed for $repo (project-root $project_rel) — see FAIL lines above"
fi

head_now="$(git -C "$repo" rev-parse HEAD 2>/dev/null)"
# PRD-build-gate-before-land requirement 4 (P0): the verdict cache below is
# keyed on the TREE, not the commit sha — a branch merged onto an unchanged
# main yields a new commit (merge or fast-forward) whose tree is identical
# to what the branch already gated, so `land` can transfer a branch verdict
# onto main's cache and have the post-land main-scope run replay it.
tree_now="$(git -C "$repo" rev-parse "$head_now^{tree}" 2>/dev/null)"
base_ref="$(resolve_base)"

# Journal path + selftest isolation guard, hoisted here (was computed just
# before the first journal write, far below) so the verdict-cache-hit path
# below — which now journals a `(cached tree=... from=...)` line instead of
# silently exiting — can use the exact same journal file and default-deny
# isolation guard a full run uses. Nothing between the old and new location
# reads $journal, so this is a pure reorder.
journal="${EXTEND_GATE_JOURNAL:-$HOME/brain/journal/build/$(date -u +%Y-%m-%d).md}"
if [ -r "$BUILD_SCRIPTS/isolation-guard.sh" ]; then
  # shellcheck source=isolation-guard.sh
  source "$BUILD_SCRIPTS/isolation-guard.sh"
else
  isolation_guard_path() { :; }
fi
isolation_guard_path "$journal" "extend-gate.sh"
mkdir -p "$(dirname "$journal")"

# PRD-build-gate-before-land requirement 1 (P0, AC1): for `--scope branch`
# the journal's `base=` field names main's own HEAD at gate start (not the
# rollback-plan tag `resolve_base` computes above, which stays the diff
# range every producer still uses unchanged) — the thing a later `land
# --gated-at` needs to compare against. Resolved from `git worktree list`
# so it works whether $repo IS the main checkout (main_sha == head_now,
# trivially) or a worktree of it (first entry is always the main worktree
# per `git worktree list`'s own contract).
journal_base_field="$base_ref"
if [ "$scope" = branch ]; then
  main_worktree_path="$(git -C "$repo" worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $2; exit}')"
  if [ -n "$main_worktree_path" ]; then
    main_sha_at_gate_start="$(git -C "$main_worktree_path" rev-parse HEAD 2>/dev/null || echo "$head_now")"
  else
    main_sha_at_gate_start="$head_now"
  fi
  journal_base_field="$main_sha_at_gate_start"
fi

if $dry_run; then
  echo "extend-gate: dry-run for $repo"
  if [ "$project_rel" = "." ]; then
    echo "  project-root: . (repo root)"
  else
    echo "  project-root: $project_rel (resolved from repo root)"
  fi
  echo "  HEAD: $head_now"
  echo "  base: $base_ref"
  echo "  parallelism: $parallelism"
  echo "  producers, in order:"
  producers_desc | sed 's/^/    - /'
  exit 0
fi

# --- per-repo integration lock ------------------------------------------
# Same lock file/convention as `worktree-extend.sh integrate`
# (<repo>/.git/autobuilder-integrate.lock via flock), so a gate run and an
# integrate on the same crate — or two gate runs — never overlap.
#
# $repo can be a `git worktree` checkout (PRD-autobuilder-gate-unstick,
# 2026-09-11): there, `$repo/.git` is a *file* pointing at the main
# checkout's `.git/worktrees/<name>`, not a directory, so a lock placed
# under it would neither create correctly nor be visible to a concurrent
# integrate/gate running against the main checkout. `git rev-parse
# --git-common-dir` resolves to the one real `.git` directory shared by
# the main checkout and every one of its worktrees, so anchoring the lock
# there keeps the "never overlap" guarantee regardless of which checkout
# a given gate run points at. Falls back to the old `$repo/.git` path if
# git can't answer (e.g. $repo isn't a git repo at all) so a missing git
# binary never turns into a gate outage.
git_common_dir=$(git -C "$repo" rev-parse --path-format=absolute --git-common-dir 2>/dev/null || echo "$repo/.git")
# PRD-build-gate-before-land requirement 1 (P0, AC1): `--scope branch`
# takes a per-slug lock instead of the shared per-crate integration lock,
# so a branch gate never contends with (or blocks) a sibling branch gate,
# or a `--scope main` run, on the same crate. Anchored at the same
# git-common-dir as the integrate lock (not the worktree's own `.git`
# file) for the same reason the integrate lock is: every worktree of one
# crate shares one common dir, so this lock is visible regardless of
# which checkout looks for it.
if [ "$scope" = branch ]; then
  lockfile="$git_common_dir/autobuilder-gate-$slug.lock"
else
  lockfile="$git_common_dir/autobuilder-integrate.lock"
fi
exec 9>"$lockfile"
# PRD-build-extend-gate-concurrent-isolation requirement 8 (P2, journal
# visibility): every run records how long it waited for producer access —
# 0 when uncontended — so a future lane-status-style summary can tell
# whether the ≤5 same-target sub-cap is actually causing gate contention
# in practice.
lock_wait_t0=$(date +%s)
if ! flock -w "$EXTEND_GATE_PRODUCER_LOCK_WAIT" 9; then
  # PRD-build-extend-gate-concurrent-isolation requirement 2: fail closed
  # with an unambiguous, actionable message naming the contending PID —
  # never proceed to read (or start writing into) a receipts dir another
  # invocation may be mid-write on. `fuser` names every PID holding an
  # open fd on the lock file; the holder that actually has it flock'd is
  # normally the sole result, but a race (holder just exited) can leave
  # none — "unknown" rather than a misleading blank in that case.
  holder_pid="$(fuser "$lockfile" 2>/dev/null | tr -s ' \t' '\n' | grep -E '^[0-9]+$' | paste -sd, -)"
  die 4 "producer-lock-contended, pid=${holder_pid:-unknown} (could not acquire integration lock for $repo within ${EXTEND_GATE_PRODUCER_LOCK_WAIT}s — another integrate/gate is running)"
fi
lock_wait=$(( $(date +%s) - lock_wait_t0 ))

# --- prune landed worktrees before producing receipts (PRD-build-worktree-targets-off-root) --
# A gate must never start on a disk full of worktrees whose branches already
# landed on origin/main (two truth-tier measure runs died to ENOSPC on
# 2026-09-08 from exactly this). Best-effort: a missing worktree-extend.sh or
# a prune failure never blocks the gate itself.
WORKTREE_EXTEND="$BUILD_SCRIPTS/worktree-extend.sh"
[ -x "$WORKTREE_EXTEND" ] && "$WORKTREE_EXTEND" prune-landed "$repo" >&2

# --- refuse a dirty tree before any producer runs (AC2) ------------------
if [ -n "$(git -C "$repo" status --porcelain)" ]; then
  die 3 "refusing — working tree at $repo is dirty"
fi

# --- refuse a --head that doesn't match actual HEAD, before any producer
#     runs (AC3) --------------------------------------------------------
if [ -n "$head_want" ] && [ "$head_want" != "$head_now" ]; then
  die 5 "refusing — HEAD is $head_now, --head asked for $head_want"
fi

# --- verdict cache (PRD-build-gate-delta-baseline P1; TREE-keyed since
#     PRD-build-gate-before-land requirement 4) --------------------------
# Keyed on (TREE sha, this script's own sha256) rather than the commit sha
# — a branch merged onto an unchanged main produces a NEW commit (a
# `--no-ff` merge commit, or a fast-forward) whose TREE is identical to
# what the branch already gated at, so `land`/`integrate` (below) can copy
# the branch's last-verdict.json onto main's cache file under the same
# tree key and have the post-land main-scope run replay it as a cache hit
# instead of re-running all 25 producers. A sibling that landed in between
# gives a genuinely different tree, so that case is correctly a miss, not
# a regression. An edit to extend-gate.sh itself (a new producer, a
# bugfix) still always invalidates a stale cached verdict via
# script_sha256, unchanged. `--record-baseline` always runs the full
# sequence; `--force` always bypasses the cache. Checked here, after the
# (cheap) dirty-tree/head-mismatch refusals above, so those refusals still
# apply to a would-be cache hit exactly as they do to a full run.
# Migration: a last-verdict.json written before this PRD has no
# `tree_sha` key, so `cached_tree` reads empty and this is correctly a
# miss once — the first fresh run rewrites the file with the tree key.
self_hash="$(sha256sum "$0" 2>/dev/null | awk '{print $1}')"
cache_file="$project_abs/target/autobuilder/last-verdict.json"
if ! $record_baseline && ! $force && [ -f "$cache_file" ]; then
  cached_tree="$(jq -r '.tree_sha // empty' "$cache_file" 2>/dev/null || true)"
  cached_hash="$(jq -r '.script_sha256 // empty' "$cache_file" 2>/dev/null || true)"
  if [ -n "$cached_tree" ] && [ "$cached_tree" = "$tree_now" ] && [ -n "$cached_hash" ] && [ "$cached_hash" = "$self_hash" ]; then
    cached_verdict="$(jq -r '.verdict // empty' "$cache_file" 2>/dev/null || true)"
    cached_rc="$(jq -r '.exit_code // empty' "$cache_file" 2>/dev/null || true)"
    if [ -n "$cached_verdict" ] && [ -n "$cached_rc" ]; then
      echo "extend-gate: verdict=$cached_verdict (cached)"
      # AC7: a cache hit journals `(cached tree=... from=...)` — `from`
      # names which scope actually produced this verdict (main, or a
      # branch's slug when `land` transferred it here), read back from
      # the cache entry's own `scope`/`slug` fields (requirement-4 write
      # below always sets them; a pre-this-PRD cache never gets here at
      # all since it has no tree_sha to match on).
      cached_from_scope="$(jq -r '.scope // "main"' "$cache_file" 2>/dev/null || echo main)"
      cached_from_slug="$(jq -r '.slug // empty' "$cache_file" 2>/dev/null || true)"
      _cache_crate_name="$(basename "$repo")"
      if [ -n "$cached_from_slug" ]; then
        printf '%s  gate  %s  %s  (cached tree=%s from=%s slug=%s)\n' \
          "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$_cache_crate_name" "$cached_verdict" "$tree_now" "$cached_from_scope" "$cached_from_slug" >>"$journal"
      else
        printf '%s  gate  %s  %s  (cached tree=%s from=%s)\n' \
          "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$_cache_crate_name" "$cached_verdict" "$tree_now" "$cached_from_scope" >>"$journal"
      fi
      exit "$cached_rc"
    fi
  fi
fi

# --- cargo-route attestation setup (P0 requirements 2/3/6, PRD-build-gate-
# cargo-route-attest) ------------------------------------------------------
# Captured HERE, before producer 1 runs, so `intended` reflects the session
# state at gate start rather than whatever state a routed producer itself
# might leave behind. Every cargo-invoking producer below (cargo_budgeted's
# `autobuilder loop` and extended-receipts.sh's 17 producers) shells
# through the burst-lane cargo shim when it's armed on $PATH, and the shim
# appends one line per invocation to $BURST_ROUTE_LOG — truncated fresh for
# THIS run so counts are per-gate, not global (requirement 2's own
# "per-gate route log isolation", AC6). BURST_LANE_PRD_SLUG attributes any
# routed cargo cost to THIS gate's own slug (requirement 6) instead of
# whatever attribution_slug_for()'s worktree-basename convention would
# otherwise guess for a main checkout that isn't a worktree at all.
crate_name="$(basename "$repo")"
route_log_file="$project_abs/target/autobuilder/route.log"
mkdir -p "$(dirname "$route_log_file")" 2>/dev/null || true
: > "$route_log_file"
export BURST_ROUTE_LOG="$route_log_file"
export BURST_LANE_PRD_SLUG="gate-$crate_name"

route_intended="local"
route_host="local"
if [ -x "$BURST_LANE_SH" ]; then
  route_status_json="$("$BURST_LANE_SH" status --json 2>/dev/null || true)"
  case "$route_status_json" in
    *'"active":true'*)
      route_intended="burst"
      route_host="$(printf '%s' "$route_status_json" | sed -n 's/.*"ip":"\([^"]*\)".*/\1/p')"
      [ -n "$route_host" ] || route_host="unknown"
      ;;
  esac
  # Structural check (ties requirement 1's PATH guard to requirement 4's
  # postcondition): does a `cargo` call under THIS process's own $PATH
  # actually reach the shim right now? Seeds $BURST_ROUTE_LOG with a
  # synthetic local/shim-not-first line when it doesn't, so the
  # postcondition below still sees the failure even in the full-bypass
  # case where the shim never runs at all to log anything about itself —
  # the exact "shim forced behind a fake real cargo" fixture (AC4).
  "$BURST_LANE_SH" route-check --repo "$repo" >&2 || true
fi

t0=$(date +%s)
blocking_notes=()
note_block() { blocking_notes+=("$1"); echo "extend-gate: $1" >&2; }

# --- per-step phase timing (PRD-build-gate-phase-timing) -----------------
# Every invoked producer below is wrapped in a `date +%s` pair and recorded
# here, in invocation order — never restructuring what a step does or its
# pass/block contribution (Non-goals: "changing any gate step's behavior,
# order, or verdict"). `record_phase <name> <seconds> <ok|skip|fail>`:
#   ok   -> journal/receipt carry the plain second count
#   skip -> the step was never invoked this run (e.g. no scripts/audit.sh,
#           gh unavailable, reviewer bypassed because a block already
#           landed) — reads `<name>:skip`, never a misleading `<name>:0`
#   fail -> the step's own subprocess exited non-zero — reads `<name>:<s>!`
# phase_names/phase_vals are parallel arrays (bash 3-compatible; no assoc
# array needed) so invocation order is preserved for free.
phase_names=()
phase_vals=()
record_phase() {  # $1=name $2=seconds $3=ok|skip|fail
  phase_names+=("$1")
  case "$3" in
    skip) phase_vals+=("skip") ;;
    fail) phase_vals+=("${2}!") ;;
    *)    phase_vals+=("$2") ;;
  esac
}

echo "extend-gate: $repo head=$head_now base=$base_ref parallelism=$parallelism"
if [ "$project_rel" = "." ]; then
  echo "extend-gate: project-root: . (repo root)"
else
  echo "extend-gate: project-root: $project_rel (resolved from repo root)"
fi

# 1. audit.sh, when the crate has one. Feeds the risk-gate receipt; a
#    non-zero exit here is logged but does not abort the run — the final
#    `autobuilder gate` is authoritative (see file header).
_phase_t0=$(date +%s)
if [ -x "$repo/scripts/audit.sh" ]; then
  if ( cd "$repo" && ./scripts/audit.sh ) 9>&-; then
    record_phase risk-gate $(( $(date +%s) - _phase_t0 )) ok
  else
    note_block "risk-gate — scripts/audit.sh exited non-zero (see risk-gate receipt for detail)"
    record_phase risk-gate $(( $(date +%s) - _phase_t0 )) fail
  fi
else
  echo "extend-gate: no scripts/audit.sh in $repo — skipping"
  record_phase risk-gate 0 skip
fi

# 2. intake — validates agent/intent-card.json against the schema and,
#    with --project, writes target/autobuilder/receipts/intake.json fresh
#    at HEAD. Before PRD-build-gate-producers, nothing in this sequence
#    ever passed --project, so intake.json was never regenerated by a
#    live gate run (intake.rs's own doc comment: validate-only "leaves no
#    files behind"). A repo with no agent/intent-card.json fails here
#    loudly, same as any other producer given a missing/invalid input —
#    no silent no-op.
_phase_t0=$(date +%s)
if ( cd "$repo" && autobuilder intake --validate agent/intent-card.json --project "$project_rel" ) 9>&-; then
  record_phase intake $(( $(date +%s) - _phase_t0 )) ok
else
  note_block "intake — autobuilder intake exited non-zero (schema violation in agent/intent-card.json, missing file, or receipt write failure — see output above)"
  record_phase intake $(( $(date +%s) - _phase_t0 )) fail
fi

# 3. proof receipt + session trace. PRD-build-cargo-budget-per-invocation:
#    runs UNSLOTTED (see run_unslotted_producer above) — the cargo test/
#    build calls it shells to each take their own budget slot for exactly
#    their own duration, not one slot for this whole (often agent-idle)
#    phase. Wedge-wrapped (requirement 7): a producer idle past
#    EXTEND_GATE_LOOP_WALL_S is killed instead of holding the gate open.
_phase_t0=$(date +%s)
if ( cd "$repo" && run_unslotted_producer autobuilder-loop \
       "$GATE_WEDGE_SH" run --budget "$EXTEND_GATE_LOOP_WALL_S" --step autobuilder-loop \
       -- autobuilder loop --project "$project_rel" --iteration 0 --head-sha "$head_now" --trace ) 9>&-; then
  record_phase proof-receipt $(( $(date +%s) - _phase_t0 )) ok
else
  _loop_rc=$?
  if [ "$_loop_rc" -eq 98 ]; then
    # gate-wedge.sh's own wedged-after-retry exit — name the wall/cpu it
    # recorded (requirement 7) rather than the generic "exited non-zero".
    _wedge_receipt="$(ls -t "$GATE_WEDGE_STATE_DIR"/*-autobuilder-loop-wedge-receipt.json 2>/dev/null | head -1)"
    _wedge_wall="?"; _wedge_cpu="?"
    if [ -n "$_wedge_receipt" ]; then
      _wedge_wall="$(jq -r '.elapsed_s // "?"' "$_wedge_receipt" 2>/dev/null)"
      _wedge_cpu="$(jq -r '[.cpu_delta_table[]? | ((.cpu_ticks_t1 // .cpu_ticks_t0) - .cpu_ticks_t0)] | add // 0' "$_wedge_receipt" 2>/dev/null)"
    fi
    note_block "proof-receipt — autobuilder loop wedged (wall=${_wedge_wall}s cpu=${_wedge_cpu})"
  else
    note_block "proof-receipt — autobuilder loop --iteration 0 exited non-zero"
  fi
  record_phase proof-receipt $(( $(date +%s) - _phase_t0 )) fail
fi

# 4. vti-plan.
_phase_t0=$(date +%s)
if ( cd "$repo" && autobuilder vti-plan --project "$project_rel" --base "$base_ref" ) 9>&-; then
  record_phase vti-plan $(( $(date +%s) - _phase_t0 )) ok
else
  note_block "vti-plan — autobuilder vti-plan exited non-zero"
  record_phase vti-plan $(( $(date +%s) - _phase_t0 )) fail
fi

# 5. rollback-plan over <base>..HEAD.
_phase_t0=$(date +%s)
if ( cd "$repo" && autobuilder rollback-plan --project "$project_rel" --base "$base_ref" ) 9>&-; then
  record_phase rollback-plan $(( $(date +%s) - _phase_t0 )) ok
else
  note_block "rollback-plan — commits since $base_ref are not all revert-clean (see target/autobuilder/rollback.md); fix forward, or a human rewrites history and says so — this script never edits history to force a pass"
  record_phase rollback-plan $(( $(date +%s) - _phase_t0 )) fail
fi

# 6. reviewer-agent: prepare, spawn the independent review headlessly via
#    `claude -p --model sonnet` (same tier /rustbuild routes it to; the
#    autobuilder binary cannot spawn a Claude subagent itself), finalize.
run_reviewer() {
  ( cd "$repo" && autobuilder reviewer-agent prepare --project "$project_rel" --base "$base_ref" ) 9>&- \
    || { note_block "reviewer-agent — prepare exited non-zero"; return 1; }
  local req="$project_abs/target/autobuilder/review-request.json"
  [ -f "$req" ] || { note_block "reviewer-agent — prepare did not write $req"; return 1; }
  command -v claude >/dev/null 2>&1 \
    || { note_block "reviewer-agent — claude CLI not on \$PATH (needed to spawn the independent review subagent)"; return 1; }
  [ -f "$REVIEWER_PROMPT" ] \
    || { note_block "reviewer-agent — missing prompt $REVIEWER_PROMPT"; return 1; }

  local out="$project_abs/target/autobuilder/review-output.json"
  local raw="$project_abs/target/autobuilder/review-output.raw.txt"
  local prompt
  prompt="$(cat "$REVIEWER_PROMPT")
---
Below is this review's target/autobuilder/review-request.json. The repo is
checked out at HEAD $head_now at $repo — read whatever you need under it.
$(cat "$req")
---
Reply with ONLY one JSON object, no prose, no markdown fences, matching
schema autobuilder.reviewer_agent_receipt.v1:
{\"schema\":\"autobuilder.reviewer_agent_receipt.v1\",\"head_sha\":\"...\",\"intent_card_sha\":\"...\",\"decision\":\"pass|concern|block\",\"block_reasons\":[...],\"concern_reasons\":[{\"id\":\"...\",\"note\":\"...\"}],\"falsification\":{\"test_audit\":\"...\",\"panic_audit\":\"...\",\"unsafe_audit\":\"...\",\"public_api_audit\":\"...\",\"deps_audit\":\"...\",\"drift_audit\":\"...\",\"counter_attack\":{\"description\":\"...\",\"test_skeleton\":\"...\"}}}"

  if ! ( cd "$repo" && claude -p "$prompt" --model sonnet --permission-mode bypassPermissions --output-format text ) 9>&- >"$raw" 2>"$raw.err"; then
    note_block "reviewer-agent — claude -p subagent invocation failed (see $raw.err)"
    return 1
  fi
  if ! python3 -c "
import json, re, sys
raw = open('$raw').read()
m = re.search(r'\{.*\}', raw, re.S)
if not m:
    sys.exit(1)
obj = json.loads(m.group(0))
json.dump(obj, open('$out', 'w'))
" 2>>"$raw.err"; then
    note_block "reviewer-agent — subagent did not return valid JSON (see $raw)"
    return 1
  fi
  ( cd "$repo" && autobuilder reviewer-agent finalize --project "$project_rel" --input "$out" ) 9>&- \
    || { note_block "reviewer-agent — finalize rejected the subagent's output"; return 1; }
}

# 7. ci-checks — needs `gh` authenticated against the pushed HEAD.
if ! command -v gh >/dev/null 2>&1; then
  note_block "ci-checks — gh CLI not on \$PATH (install: https://cli.github.com)"
  record_phase ci-checks 0 skip
elif ! gh auth status >/dev/null 2>&1; then
  note_block "ci-checks — gh not authenticated: run 'gh auth login'"
  record_phase ci-checks 0 skip
else
  _phase_t0=$(date +%s)
  if ( cd "$repo" && autobuilder ci-checks --project "$project_rel" ) 9>&-; then
    record_phase ci-checks $(( $(date +%s) - _phase_t0 )) ok
  else
    note_block "ci-checks — workflow(s) on HEAD are not green, or still pending (the next tick retries)"
    record_phase ci-checks $(( $(date +%s) - _phase_t0 )) fail
  fi
fi

# 8. the 17 extended-gates producers, in parallel. Passed the RESOLVED
# project path (not $repo) so their receipts land in the same
# target/autobuilder/receipts/ the rest of this script's producers and
# the final `autobuilder gate` read from.
# subshell wraps the direct exec so 9>&- has a scope to apply to — this
# call is not otherwise inside a `( ... )` group.
# PRD-build-cargo-budget-per-invocation: runs UNSLOTTED (see
# run_unslotted_producer above) — the internal $parallelism fan-out no
# longer takes one cargo-budget slot for the whole phase; each of the 17
# producers' own real cargo calls takes its own slot for exactly its own
# duration instead.
_phase_t0=$(date +%s)
if ( run_unslotted_producer extended-receipts "$RUSTBUILD_SCRIPTS/extended-receipts.sh" "$project_abs" "$parallelism" ) 9>&-; then
  record_phase receipts $(( $(date +%s) - _phase_t0 )) ok
else
  note_block "extended-receipts — one or more extended producers did not pass|skip (see output above)"
  record_phase receipts $(( $(date +%s) - _phase_t0 )) fail
fi

# 9. the risk gate itself — authoritative pass/block, reads all 25 receipts.
# Quota guard (Joe 2026-09-11): the reviewer is a Sonnet `claude -p` call. It runs LAST, and only
# when every other producer passed — a red gate never pays for a review it cannot use. The next gate
# on a fixed HEAD runs it. On 2026-09-11 five reviewer runs shipped nothing.
_phase_t0=$(date +%s)
if [ "${#blocking_notes[@]}" -eq 0 ]; then
  if run_reviewer; then
    record_phase reviewer $(( $(date +%s) - _phase_t0 )) ok
  else
    record_phase reviewer $(( $(date +%s) - _phase_t0 )) fail
  fi
else
  echo "extend-gate: reviewer skipped — ${#blocking_notes[@]} block(s) already recorded (no Sonnet spend on a red gate)"
  echo "$(date -u +%FT%TZ)  gate  ${repo##*/}  reviewer-skipped  (blocks=${#blocking_notes[@]} head=${head_now:0:7})" >> "$HOME/brain/journal/build/$(date -u +%F).md"
  record_phase reviewer 0 skip
fi
_phase_t0=$(date +%s)
gate_out="$(exec 9>&-; cd "$repo" && autobuilder gate --project "$project_rel" 2>&1)"
gate_rc=$?
if [ "$gate_rc" -eq 0 ]; then
  record_phase gate $(( $(date +%s) - _phase_t0 )) ok
else
  record_phase gate $(( $(date +%s) - _phase_t0 )) fail
fi
printf '%s\n' "$gate_out"
summary="$(printf '%s\n' "$gate_out" | grep -m1 '^gate: ' || true)"

# --- cargo-route postcondition (P0 requirement 4, AC4) --------------------
# Route log fields (requirement 2): <ts> <pid> <subcommand> <decision>
# <cause> <cwd>. A routed subcommand that stayed local while intended=burst
# is a silent regression — the whole reason this PRD exists — so it is
# journaled by name (never just a block, per the PRD's Non-goals: "a route
# mismatch is a journaled guard event, never a block").
route_burst_n=0; route_local_n=0; route_passthrough_n=0; route_first_local_cause=""
if [ -f "$route_log_file" ]; then
  route_burst_n="$(awk '$4=="burst"{n++} END{print n+0}' "$route_log_file")"
  route_local_n="$(awk '$4=="local"{n++} END{print n+0}' "$route_log_file")"
  route_passthrough_n="$(awk '$4=="passthrough"{n++} END{print n+0}' "$route_log_file")"
  route_first_local_cause="$(awk '$4=="local"{print $5; exit}' "$route_log_file")"
fi
route_mismatch=false
if [ "$route_intended" = "burst" ] && [ "$route_local_n" -gt 0 ]; then
  route_mismatch=true
  probe_emit gate-cargo-route dirty "route-mismatch intended=$route_intended burst=$route_burst_n local=$route_local_n cause=${route_first_local_cause:-unknown}" >/dev/null
elif [ "$route_intended" = "burst" ]; then
  probe_emit gate-cargo-route clean "intended=burst burst=$route_burst_n local=0" >/dev/null
else
  probe_emit gate-cargo-route clean "intended=local — nothing to route" >/dev/null
fi

wall=$(( $(date +%s) - t0 ))
blockers_csv=""
if [ "${#blocking_notes[@]}" -gt 0 ]; then
  blockers_csv="$(IFS='|'; echo "${blocking_notes[*]}")"
fi

# --- phase timing summary (PRD-build-gate-phase-timing) -------------------
# Builds `phases=<name>:<val>,...` in invocation order from the
# record_phase calls above, and checks the sum of every non-skipped phase's
# seconds (a fail's own `!`-suffixed seconds still count toward the sum —
# only `skip` is excluded, requirement: "a phase that fails or is skipped
# is recorded as such, never as zero") against `wall` within 5%; anything
# wider is surfaced as `unattributed:<s>` rather than silently dropped
# (requirement: "the sum of phase seconds is within 5% of wall or the line
# carries unattributed:<s>").
phases_str=""
phase_sum=0
for _pi in "${!phase_names[@]}"; do
  _pname="${phase_names[$_pi]}"
  _pval="${phase_vals[$_pi]}"
  case "$_pval" in
    skip) : ;;
    *!)   phase_sum=$(( phase_sum + ${_pval%!} )) ;;
    *)    phase_sum=$(( phase_sum + _pval )) ;;
  esac
  if [ -n "$phases_str" ]; then phases_str="$phases_str,$_pname:$_pval"; else phases_str="$_pname:$_pval"; fi
done
phase_unattributed=$(( wall - phase_sum ))
[ "$phase_unattributed" -lt 0 ] && phase_unattributed=0
phase_tolerance=0
[ "$wall" -gt 0 ] && phase_tolerance=$(( wall * 5 / 100 ))
phase_over_tolerance=false
phases_field="phases=$phases_str"
if [ "$phase_unattributed" -gt "$phase_tolerance" ]; then
  phase_over_tolerance=true
  phases_field="$phases_field,unattributed:$phase_unattributed"
fi

# --- attribution (P0 requirement 1, PRD-build-gate-debt-auto-prd) --------
# Split blocking_notes into in-scope (the building PRD's own diff touched
# it) vs inherited (landed by an earlier merge). The diff range is the
# building PRD's own merge: when HEAD is a no-ff merge commit (two
# parents), that's exactly <head>^1..<head> — the merge's first parent is
# mainline immediately before this PRD landed, so the diff against it is
# what the PRD's own merge introduced (Technical considerations: "the
# archive line already records base=... and the merge sha, so git
# merge-base gives the diff range"). A non-merge HEAD (e.g. a fast-forward
# land, or a gate run ahead of any merge) has no such single-parent split,
# so this falls back to the wider $base_ref..HEAD range — less surgical,
# but never crashes attribution into treating a fast-forwarded PRD's own
# changes as "no diff at all".
attribution_json=""
attribution_inherited=0
attribution_in_scope=0
if [ "${#blocking_notes[@]}" -gt 0 ] && [ -x "$GATE_ATTRIBUTION" ]; then
  attr_diff_base="$base_ref"
  parent_count="$(git -C "$repo" rev-list --parents -n1 "$head_now" 2>/dev/null | awk '{print NF-1}')"
  if [ "${parent_count:-0}" -eq 2 ]; then
    attr_diff_base="${head_now}^1"
  fi
  attr_notes_file="$(mktemp "${TMPDIR:-/tmp}/extend-gate-attr-notes.XXXXXX")"
  for n in "${blocking_notes[@]}"; do
    # note_block strings are always "<receipt> — <detail>" (em dash,
    # consistent across every note_block call above); split on the first
    # occurrence so a detail that itself contains " — " stays intact.
    printf '%s\n' "$n" | sed -E 's/^([^ ]+) — (.*)$/\1\t\2/' >> "$attr_notes_file"
  done
  if attr_out="$("$GATE_ATTRIBUTION" compute "$repo" "$attr_diff_base" "$head_now" "$attr_notes_file" 2>/dev/null)"; then
    attribution_json="$attr_out"
    attribution_in_scope="$(python3 -c 'import json,sys; print(json.loads(sys.argv[1]).get("in_scope",0))' "$attribution_json" 2>/dev/null || echo 0)"
    attribution_inherited="$(python3 -c 'import json,sys; print(json.loads(sys.argv[1]).get("inherited",0))' "$attribution_json" 2>/dev/null || echo 0)"
  fi
  rm -f "$attr_notes_file"
fi
# $journal was resolved (and the selftest isolation guard applied) right
# after $head_now above, PRD-build-gate-before-land requirement 4 — the
# verdict-cache-hit early-exit needs it too now, so it moved earlier
# instead of being duplicated. Kept as a no-op here (mkdir -p is
# idempotent) in case a future edit reorders things again.
mkdir -p "$(dirname "$journal")"

# --- record-baseline: write agent/gate-baseline.json from THIS run's
# blocking set, print it, done. Never computes or acts on a delta verdict
# — recording and shipping are separate, deliberate acts (design note:
# "the gate never auto-widens a baseline"). ---------------------------
gate_out_file="$(mktemp "${TMPDIR:-/tmp}/extend-gate-out.XXXXXX")"
printf '%s\n' "$gate_out" > "$gate_out_file"

if $record_baseline; then
  recorded="$("$GATE_DELTA" record "$repo" "$gate_out_file")" || { rm -f "$gate_out_file"; die 2 "gate-delta.sh record failed"; }
  rm -f "$gate_out_file"
  echo "extend-gate: recorded baseline to $repo/agent/gate-baseline.json"
  printf '%s\n' "$recorded"
  # scope_prefix is empty for the default `--scope main` (unchanged output);
  # `--scope branch` prepends `scope=branch slug=<slug> ` and swaps in
  # $journal_base_field (main's HEAD at gate start) for the base= token
  # (requirement 1, AC1).
  scope_prefix=""
  [ "$scope" = branch ] && scope_prefix="scope=branch slug=$slug "
  printf '%s  gate  %s  record-baseline  (%shead=%s base=%s %s wall=%ss %s lock_wait=%ss cargo=burst:%s/local:%s)\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$crate_name" "$scope_prefix" "$head_now" "$journal_base_field" \
    "${summary:-gate: no-summary-line}" "$wall" "$phases_field" "$lock_wait" "$route_burst_n" "$route_local_n" >>"$journal"
  if $route_mismatch; then
    printf '%s  gate  route-mismatch  (intended=%s burst=%s local=%s cause=%s)\n' \
      "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$route_intended" "$route_burst_n" "$route_local_n" "${route_first_local_cause:-unknown}" >>"$journal"
  fi
  exit 0
fi

# --- delta verdict against the committed baseline (PRD-build-gate-delta-baseline) ---
# `gate-delta.sh verdict`'s own exit code already mirrors <gate_rc>
# byte-for-byte whenever there is no committed baseline (see that
# script's header) — using it unconditionally as this script's final
# exit code is what makes the absent-baseline path identical to the
# pre-this-PRD behavior. Only the PRESENT-baseline path prints or
# journals anything new.
delta_out="$("$GATE_DELTA" verdict "$repo" "$gate_out_file" "$gate_rc")"
delta_rc=$?
rm -f "$gate_out_file"
baseline_state="$(printf '%s\n' "$delta_out" | sed -n 's/^baseline=//p')"
delta_verdict="$(printf '%s\n' "$delta_out" | sed -n 's/^verdict=//p')"
new_blocks="$(printf '%s\n' "$delta_out" | sed -n 's/^new_blocks=//p')"
inherited_blocks="$(printf '%s\n' "$delta_out" | sed -n 's/^inherited_blocks=//p')"

final_rc="$delta_rc"
outcome="pass"; [ "$gate_rc" -eq 0 ] || outcome="block"
journal_suffix=""
if [ "$baseline_state" = "present" ]; then
  echo "extend-gate: delta verdict=$delta_verdict baseline=present new_blocks=${new_blocks:-none} inherited_blocks=${inherited_blocks:-none}"
  outcome="$delta_verdict"
  journal_suffix=" verdict=$delta_verdict inherited_blocks=[${inherited_blocks}]"
fi
# Attribution suffix (requirement 1, AC1: "the journal gate line reads
# inherited=1 in-scope=1") — appended whenever this run had at least one
# blocking note, independent of the baseline-delta suffix above (a
# different axis: "known before" vs "whose diff introduced it").
if [ "${#blocking_notes[@]}" -gt 0 ]; then
  journal_suffix="$journal_suffix inherited=$attribution_inherited in-scope=$attribution_in_scope"
fi

# One journal line per gate run (requirement 8 / AC13): crate, HEAD, base
# tag, pass/block counts, blocking receipt names, wall seconds, (PRD-
# build-gate-phase-timing) a per-step phase breakdown right after wall=,
# (PRD-build-extend-gate-concurrent-isolation requirement 8 / P2) how long
# this run waited for producer access before it started (0 when
# uncontended), and (requirement 5 / AC5, PRD-build-gate-cargo-route-attest)
# how many of this run's routed cargo calls actually reached the box vs
# stayed local.
scope_prefix=""
[ "$scope" = branch ] && scope_prefix="scope=branch slug=$slug "
printf '%s  gate  %s  %s  (%shead=%s base=%s %s blocking=%s wall=%ss %s lock_wait=%ss cargo=burst:%s/local:%s)%s\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$crate_name" "$outcome" "$scope_prefix" "$head_now" "$journal_base_field" \
  "${summary:-gate: no-summary-line}" "${blockers_csv:-none}" "$wall" "$phases_field" "$lock_wait" \
  "$route_burst_n" "$route_local_n" "$journal_suffix" >>"$journal"

# A route mismatch is a journaled guard event, never a block (Non-goals) —
# the verdict computed above is unaffected either way (requirement 4, AC4).
if $route_mismatch; then
  printf '%s  gate  route-mismatch  (intended=%s burst=%s local=%s cause=%s)\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$route_intended" "$route_burst_n" "$route_local_n" "${route_first_local_cause:-unknown}" >>"$journal"
fi

# --- write the verdict cache (P1) — every full run, pass/delta-pass/block
# alike, so a repeat invocation at the same head + same script replays
# instead of regenerating. Now also carries `cargo_route` (P0 requirement
# 3, PRD-build-gate-cargo-route-attest) so a cache hit still replays an
# accurate attestation instead of silently dropping it. ------------------
cache_verdict_val="$outcome"
mkdir -p "$(dirname "$cache_file")"
# attribution_json defaults to an empty blocks/counts object when this run
# had no blocking notes, or gate-attribution.sh wasn't runnable — the
# summary receipt always has the key, never sometimes-present (requirement
# 1: "the tags land in the summary receipt").
attribution_empty='{"blocks":[],"in_scope":0,"inherited":0}'
attribution_for_cache="${attribution_json:-$attribution_empty}"
# Phase timing (PRD-build-gate-phase-timing requirement: "the gate receipt
# ... gains a phases object with the same values plus wall_s and head") —
# built from the same phase_names/phase_vals arrays the journal line's
# phases_field above reads, so receipt and journal never disagree.
phases_json='{}'
for _pi in "${!phase_names[@]}"; do
  phases_json="$(jq -c --arg k "${phase_names[$_pi]}" --arg v "${phase_vals[$_pi]}" '. + {($k): $v}' <<<"$phases_json")"
done
jq -n --arg head "$head_now" --arg tree "$tree_now" --arg hash "$self_hash" --arg verdict "$cache_verdict_val" \
     --argjson rc "$final_rc" --arg new "$new_blocks" --arg inh "$inherited_blocks" \
     --arg intended "$route_intended" --argjson burst "$route_burst_n" \
     --argjson local "$route_local_n" --argjson passthrough "$route_passthrough_n" \
     --arg host "$route_host" --argjson attribution "$attribution_for_cache" \
     --argjson phases "$phases_json" --argjson wall_s "$wall" \
     --arg scope "$scope" --arg slug "$slug" \
     --argjson over "$phase_over_tolerance" --argjson unattr "$phase_unattributed" '
  {
    head_sha: $head,
    head: $head,
    tree_sha: $tree,
    script_sha256: $hash,
    verdict: $verdict,
    exit_code: $rc,
    new_blocks: ($new | if . == "" then [] else split(",") end),
    inherited_blocks: ($inh | if . == "" then [] else split(",") end),
    cargo_route: {intended: $intended, burst: $burst, local: $local, passthrough: $passthrough, host: $host},
    blocks: $attribution.blocks,
    attribution: {in_scope: $attribution.in_scope, inherited: $attribution.inherited},
    phases: $phases,
    wall_s: $wall_s,
    scope: $scope,
    slug: $slug
  } + (if $over then {unattributed_s: $unattr} else {} end)
' > "$cache_file" 2>/dev/null || true

# --- best-effort: merge cargo_route into autobuilder's own release
# receipt too (target/autobuilder/receipts/<head_sha>.json — gate.rs's
# ReceiptPath::HeadShaJson), when the `autobuilder gate` run above actually
# wrote one, so a reviewer reading the receipt directly (not just
# last-verdict.json) sees the same attestation (P0 requirement 3). autobuilder
# itself is a separate crate this PRD's Engineering target does not touch —
# this is a non-destructive jq merge onto whatever it already wrote, never a
# schema change, and fails open (never blocks the gate) if the file is
# absent or jq can't merge it.
release_receipt="$project_abs/target/autobuilder/receipts/${head_now}.json"
if [ -f "$release_receipt" ]; then
  release_receipt_tmp="$(mktemp "${TMPDIR:-/tmp}/extend-gate-receipt.XXXXXX")"
  if jq --arg intended "$route_intended" --argjson burst "$route_burst_n" \
        --argjson local "$route_local_n" --argjson passthrough "$route_passthrough_n" \
        --arg host "$route_host" \
        '. + {cargo_route: {intended: $intended, burst: $burst, local: $local, passthrough: $passthrough, host: $host}}' \
        "$release_receipt" > "$release_receipt_tmp" 2>/dev/null; then
    mv "$release_receipt_tmp" "$release_receipt"
  else
    rm -f "$release_receipt_tmp"
  fi
fi

exit "$final_rc"
