#!/usr/bin/env bash
# scripts-index-gen.sh — PRD-build-branch-contract-split requirement 8
# (P2): generate docs/scripts-index.md, one line per scripts/*.sh, pulled
# from that script's own header comment (line 2, right after the
# shebang — every script in this repo follows the convention
# `# <name> — <description>`, so this reads the same text a human
# already sees when opening the file, never a second copy of it). A
# script whose line 2 is not a `#`-comment (missing shebang-adjacent
# header, or a blank/code line there instead) is listed under its own
# "Undocumented" section instead of silently dropped — this is the
# mechanism SKILL.md's index points at instead of enumerating all
# ~200 scripts inline.
#
# Usage: scripts-index-gen.sh [--check]
#   (no args)  regenerate docs/scripts-index.md and exit 0.
#   --check    regenerate into a temp file and diff against the committed
#              docs/scripts-index.md; exit 1 (naming the diff) if stale,
#              0 if up to date. Never writes the real file in this mode.
#
# Exit: 0 generated/up to date | 1 --check found the file stale |
#       2 usage error
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
OUT="$REPO_ROOT/docs/scripts-index.md"

CHECK=0
case "${1:-}" in
  "") ;;
  --check) CHECK=1 ;;
  *) echo "scripts-index-gen: unknown arg: $1" >&2; exit 2 ;;
esac

gen() {
  local f base line2 desc
  echo "# Scripts index"
  echo
  echo "Generated by \`scripts/scripts-index-gen.sh\` — do not hand-edit. One"
  echo "line per \`scripts/*.sh\`, pulled from that script's own header"
  echo "comment (never a second copy of it — SKILL.md's Scripts section"
  echo "points here instead of listing scripts inline)."
  echo
  local -a documented=() undocumented=()
  for f in "$REPO_ROOT"/scripts/*.sh; do
    [ -f "$f" ] || continue
    base="$(basename "$f")"
    line2="$(sed -n '2p' "$f")"
    if [[ "$line2" =~ ^#\ (.*)$ ]]; then
      desc="${BASH_REMATCH[1]}"
      # Every script's header already opens with its own name (bare, or
      # with a usage suffix like "archive-commit.sh <slug>") before the
      # em/en-dash separator — strip that lead-in so the index line
      # doesn't repeat the path we already printed. Falls back to the
      # raw comment text unchanged when the header doesn't follow the
      # convention closely enough to match.
      stem="${base%.sh}"
      if [[ "$desc" =~ ^${stem}(\.sh)?[^—-]*[—-]+[[:space:]]*(.*)$ ]]; then
        desc="${BASH_REMATCH[2]}"
      fi
      documented+=("- \`scripts/$base\` — $desc")
    else
      undocumented+=("- \`scripts/$base\`")
    fi
  done
  echo "## Scripts"
  echo
  printf '%s\n' "${documented[@]}"
  echo
  echo "## Undocumented"
  echo
  if [ "${#undocumented[@]}" -eq 0 ]; then
    echo "(none — every scripts/*.sh has a header comment on line 2)"
  else
    printf '%s\n' "${undocumented[@]}"
  fi
}

if [ "$CHECK" -eq 1 ]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  gen > "$tmp"
  if [ -f "$OUT" ] && diff -q "$tmp" "$OUT" >/dev/null 2>&1; then
    echo "scripts-index-gen: docs/scripts-index.md is up to date"
    exit 0
  fi
  echo "scripts-index-gen: docs/scripts-index.md is stale:" >&2
  diff -u "$OUT" "$tmp" 2>&1 | head -40 >&2
  exit 1
fi

gen > "$OUT"
echo "scripts-index-gen: wrote $OUT"
